---
sidebar: sidebar 
permalink: rn/about.html 
keywords: about, about this release, current release 
summary: 'La documentation de ce site décrit l"API REST Astra Control et les technologies d"automatisation associées disponibles avec Astra Control.' 
---
= À propos de cette version
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La documentation de ce site décrit l'API REST d'Astra Control et les technologies d'automatisation connexes, incluses dans les versions les plus récentes des deux modèles de déploiement d'Astra Control.


NOTE: Un numéro de version du formulaire *YY.MM* est attribué à chaque version Astra. Cette valeur permet d'identifier la version basée sur l'année (_YY_) et le mois (_MM_) qu'elle est devenue disponible. Par exemple, Astra Control Service 23.01 a été lancé en janvier 2023.

.Cadence de sortie
En général, des mises à jour du service Astra Control et du centre de contrôle Astra sont effectuées en même temps. Cependant, Astra Control Service a une cadence de sortie accélérée qui peut entraîner une ou plusieurs mises à jour incrémentielles au-delà de la dernière version d'Astra Control Center.

Comme ce site documente l'API REST pour les deux modèles de déploiement, certaines fonctionnalités peuvent être disponibles uniquement avec la version la plus récente d'Astra Control Service. Les différences entre les deux modèles de déploiement sont notées selon les besoins.

.Les déploiements d'Astra Control
La documentation de ce site s'applique aux versions suivantes d'Astra Control :

* Service de contrôle Astra 23.01
* Astra Control Center 22.11


.Plus d'informations
Consultez les pages et sites suivants pour obtenir de plus amples renseignements sur les versions actuelles et précédentes d'Astra Control.

* link:../rn/whats_new.html["Nouveautés de l'API REST Astra Control"]
* link:../endpoints/resources.html["Ressources REST et terminaux"]
* https://docs.netapp.com/us-en/astra-control-center/["Documentation Astra Control Center 22.11"^]
* https://docs.netapp.com/us-en/astra-control-service/["Documentation relative à Astra Control Service 23.01"^]
* link:../aa-earlier-versions.html["Versions antérieures de la documentation d'Astra Automation"]


.Aidez-nous à améliorer la documentation
Suivez-nous sur Twitter *@NetAppDoc* pour recevoir des notifications sur la documentation NetApp. Vous pouvez également nous faire part de vos commentaires en devenant un link:https://docs.netapp.com/us-en/contribute/["Contributeur GitHub"^] ou en envoyant un e-mail à _doccomments@netapp.com_.
