---
sidebar: sidebar 
permalink: rn/about.html 
keywords: about, about this release, current release 
summary: 'La documentation de ce site décrit l"API REST Astra Control et les technologies d"automatisation associées disponibles avec Astra Control.' 
---
= À propos de cette version
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La documentation de ce site décrit l'API REST d'Astra Control et les technologies d'automatisation connexes, incluses dans les versions les plus récentes des deux modèles de déploiement d'Astra Control.


NOTE: Un numéro de version du formulaire *YY.MM* est attribué à chaque version d'Astra Control. Cette valeur permet d'identifier la version basée sur l'année (_YY_) et le mois (_MM_) qu'elle est devenue disponible. Par exemple, Astra Control Center 23.04 a été publiée en avril 2023.

.Cadence de sortie
En général, des mises à jour du service Astra Control et du centre de contrôle Astra sont effectuées en même temps. Cependant, le rythme accéléré des versions d'Astra Control Service peut entraîner l'installation d'une ou de plusieurs mises à jour incrémentielles au-delà de la version la plus récente d'Astra Control Center.

Comme ce site documente l'API REST pour les deux modèles de déploiement, certaines fonctionnalités peuvent être disponibles uniquement avec la version la plus récente d'Astra Control Service. Les différences entre les deux modèles de déploiement sont notées selon les besoins.

.Les déploiements d'Astra Control
La documentation de ce site s'applique aux versions suivantes d'Astra Control :

* ASTRA Control Service 23.06
* ASTRA Control Center 23.04


.Plus d'informations
Consultez les pages et sites suivants pour obtenir de plus amples renseignements sur les versions actuelles et précédentes d'Astra Control.

* link:../rn/whats_new.html["Nouveautés de l'API REST Astra Control"]
* link:../endpoints/resources.html["Ressources REST et terminaux"]
* https://docs.netapp.com/us-en/astra-control-center/["Documentation d'Astra Control Center 23.04"^]
* https://docs.netapp.com/us-en/astra-control-service/["Documentation d'Astra Control Service 23.06"^]
* link:../aa-earlier-versions.html["Versions antérieures de la documentation d'Astra Automation"]


.Aidez-nous à améliorer la documentation
Suivez-nous sur Twitter *@NetAppDoc* pour recevoir des notifications sur la documentation NetApp. Vous pouvez également nous faire part de vos commentaires en devenant un link:https://docs.netapp.com/us-en/contribute/["Contributeur GitHub"^] ou en envoyant un e-mail à _doccomments@netapp.com_.
