---
sidebar: sidebar 
permalink: workflows_infra/wf_ldap_disable_reset.html 
keywords:  
summary: 'Il existe deux tâches administratives facultatives, bien que liées, que vous pouvez effectuer selon vos besoins pour un déploiement de centre de contrôle Astra. Vous pouvez désactiver globalement l"authentification LDAP et réinitialiser la configuration LDAP.' 
---
= Désactivez et réinitialisez LDAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Il existe deux tâches administratives facultatives, bien que liées, que vous pouvez effectuer selon vos besoins pour un déploiement de centre de contrôle Astra. Vous pouvez désactiver globalement l'authentification LDAP et réinitialiser la configuration LDAP.

Les deux tâches de flux de travail requièrent l'ID pour le `astra.account.ldap` Réglage Astra. Les détails sur la récupération de l'ID de paramètre sont inclus dans *configurer le serveur LDAP*. Voir link:../workflows_infra/wf_ldap_configure_server.html#3-retrieve-the-uuid-of-the-ldap-setting["Récupère l'UUID du paramètre LDAP"] pour en savoir plus.

* link:../workflows_infra/wf_ldap_disable_reset.html#disable-ldap-authentication["Désactivez l'authentification LDAP"]
* link:../workflows_infra/wf_ldap_disable_reset.html#reset-the-ldap-authentication-configuration["Réinitialisez la configuration de l'authentification LDAP"]




== Désactivez l'authentification LDAP

Vous pouvez effectuer l'appel d'API REST suivant pour désactiver globalement l'authentification LDAP pour un déploiement Astra spécifique. L'appel met à jour le `astra.account.ldap` réglage et `isEnabled` la valeur est définie sur `false`.

[cols="1,6"]
|===
| Méthode HTTP | Chemin 


| EN | /accounts/{account_id}/core/v1/settings/{setting_id} 
|===


===== Exemple d'entrée JSON

[source, json]
----
{
  "type": "application/astra-setting",
  "version": "1.0",
  "desiredConfig": {
    "connectionHost": "myldap.example.com",
    "credentialId": "3bd9c8a7-f5a4-4c44-b778-90a85fc7d154",
    "groupBaseDN": "OU=groups,OU=astra,DC=example,DC=com",
    "isEnabled": "false",
    "port": 686,
    "secureMode": "LDAPS",
    "userBaseDN": "OU=users,OU=astra,DC=example,dc=com",
    "userSearchFilter": "((objectClass=User))",
    "vendor": "Active Directory"
    }
}
----
[source, curl]
----
curl --location -i --request PUT --data @JSONinput 'https://astra.example.com/accounts/<ACCOUNT_ID>/core/v1/settings/<SETTING_ID>' --header 'Content-Type: application/astra-setting+json' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>'
----
Si l'appel a réussi, le `HTTP 204` la réponse est renvoyée. Vous pouvez éventuellement récupérer à nouveau les paramètres de configuration pour confirmer la modification.



== Réinitialisez la configuration de l'authentification LDAP

Vous pouvez effectuer l'appel d'API REST suivant pour déconnecter Astra du serveur LDAP et réinitialiser la configuration LDAP dans Astra. L'appel met à jour le `astra.account.ldap` réglage et valeur de `connectionHost` est effacé.

La valeur de `isEnabled` doit également être défini sur `false`. Vous pouvez soit définir cette valeur avant d'effectuer l'appel de réinitialisation, soit dans le cadre de l'appel de réinitialisation. Dans le deuxième cas, `connectionHost` doit être effacé et `isEnabled` défini sur false lors du même appel de réinitialisation.


CAUTION: Il s'agit d'une opération perturbatrice et vous devez procéder avec précaution. Elle supprime tous les utilisateurs et groupes LDAP importés. Il supprime également tous les utilisateurs, groupes et liaisons Astra (type LDAP) associés que vous avez créés dans Astra Control Center.

[cols="1,6"]
|===
| Méthode HTTP | Chemin 


| EN | /accounts/{account_id}/core/v1/settings/{setting_id} 
|===


===== Exemple d'entrée JSON

[source, json]
----
{
  "type": "application/astra-setting",
  "version": "1.0",
  "desiredConfig": {
    "connectionHost": "",
    "credentialId": "3bd9c8a7-f5a4-4c44-b778-90a85fc7d154",
    "groupBaseDN": "OU=groups,OU=astra,DC=example,DC=com",
    "isEnabled": "false",
    "port": 686,
    "secureMode": "LDAPS",
    "userBaseDN": "OU=users,OU=astra,DC=example,dc=com",
    "userSearchFilter": "((objectClass=User))",
    "vendor": "Active Directory"
    }
}
----
Notez ce qui suit :

* Pour modifier le serveur LDAP, vous devez à la fois désactiver et réinitialiser la modification LDAP `connectHost` à une valeur nulle comme indiqué dans l'exemple ci-dessus.


[source, curl]
----
curl --location -i --request PUT --data @JSONinput 'https://astra.example.com/accounts/<ACCOUNT_ID>/core/v1/settings/<SETTING_ID>' --header 'Content-Type: application/astra-setting+json' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>'
----
Si l'appel a réussi, le `HTTP 204` la réponse est renvoyée. Vous pouvez éventuellement récupérer à nouveau la configuration pour confirmer la modification.
