---
sidebar: sidebar 
permalink: workflows_infra/wf_man_cluster.html 
keywords:  
summary: 'Vous pouvez gérer un cluster Kubernetes afin d"effectuer des opérations de protection des données.' 
---
= Gérer un cluster
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez gérer un cluster Kubernetes afin d'assurer la protection des données.



=== 1. Sélectionnez le cluster à gérer

Exécutez le flux de travail link:../workflows_infra/wf_list_clusters.html["Lister les clusters"] et sélectionnez le cluster souhaité. La propriété `managedState` du cluster doit être `unmanaged`.



=== 2. Sélectionnez éventuellement la classe de stockage

Éventuellement, exécutez le flux de travail link:../workflows_infra/wf_list_storage_classes.html["Répertorier les classes de stockage"] et sélectionnez la classe de stockage souhaitée.


NOTE: Si vous ne fournissez pas de classe de stockage à l'appel pour gérer le cluster, votre classe de stockage par défaut sera utilisée.



=== 3. Gérez le cluster

Effectuez l'appel d'API REST suivant pour gérer le cluster.

[cols="1,6"]
|===
| Méthode HTTP | Chemin 


| POST | /Accounts/{account_ID}/topologique/v1/managedclusters 
|===


===== Exemple d'entrée JSON

[source, json]
----
{
  "type": "application/astra-managedCluster",
  "version": "1.0",
  "id": "d0fdf455-4330-476d-bb5d-4d109714e07d"
}
----


===== Exemple de boucle

[source, curl]
----
curl --location -i --request POST 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/topology/v1/managedClusters' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>' --data @JSONinput
----