---
sidebar: sidebar 
permalink: workflows_infra/workflows_infra_before.html 
keywords: workflows, infrastructure workflows, preparation 
summary: 'Vous pouvez utiliser ces workflows pour créer et entretenir l"infrastructure utilisée avec un déploiement d"Astra Control Center. Dans de nombreux cas, les flux de travail peuvent également être utilisés avec le service Astra Control.' 
---
= Avant de commencer
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez utiliser ces workflows pour créer et entretenir l'infrastructure utilisée avec un déploiement d'Astra Control Center. Dans de nombreux cas, les flux de travail peuvent également être utilisés avec le service Astra Control.


NOTE: Il est possible de développer et d'améliorer ces flux de travail par NetApp à tout moment, et nous vous recommandons de les consulter régulièrement.



== Préparation générale

Avant d'utiliser l'un des flux de travail Astra, veillez à le lire link:../get-started/prepare_to_use_workflows.html["Préparez l'utilisation des workflows"].



== Catégories de flux de travail

Les workflows d'infrastructure sont organisés selon différentes catégories, pour faciliter la localisation.

[cols="25,75"]
|===
| Catégorie | Description 


| Identité et accès | Ces flux de travail vous permettent de gérer les identités et d'accéder à Astra. Les ressources comprennent les utilisateurs, les informations d'identification et les jetons. 


| Configuration LDAP | Vous pouvez configurer Astra Control Center pour qu'il utilise LDAP pour authentifier les utilisateurs sélectionnés. 


| Clusters | Vous pouvez ajouter des clusters Kubernetes gérés, ce qui vous permet de protéger et de prendre en charge les applications qu'ils contiennent. 


| Cloud | Ces workflows permettent d'accéder aux clouds disponibles via l'API REST d'Astra Control. 


| Seaux | Vous pouvez utiliser ces workflows pour créer et gérer les compartiments S3 utilisés pour stocker les sauvegardes. 


| Stockage | Ces workflows permettent d'ajouter et de gérer des volumes et des systèmes back-end de stockage. 
|===