---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-core-v1-subscriptions.html 
summary: Lister tous les abonnements 
---
= Lister tous les abonnements
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/subscriptions`#

Renvoie un tableau JSON contenant toutes les ressources correspondantes de la collection. Si des champs individuels sont spécifiés dans la requête, le tableau JSON items contiendra les champs demandés pour chaque ressource correspondante dans l'ordre indiqué.



== Paramètres

[cols="5*"]
|===
| Nom | Type | Dans | Obligatoire | Description 


| identifiant_compte | chaîne | chemin | Vrai  a| 
ID de la ressource de compte conteneur

* exemple: {{.Account}}




| continuer |  | requête | Faux  a| 
Indique le jeton à partir duquel reprendre la liste.

Exemples d'URL : « continue=+++<continue token="" from="" collection="" metadata="">+++ »+++</continue>+++

Exemples OpenAPI : "+++<continue token="" from="" collection="" metadata="">+++"+++</continue>+++</continue>



| nombre | chaîne | requête | Faux  a| 
Indique si le nombre total de ressources doit être renvoyé dans l'objet métadonnées.

Exemples d'URL : « count=true »

Exemples OpenAPI : "true"



| filtre | chaîne | requête | Faux  a| 
Indique les champs qui doivent être mis en correspondance pour renvoyer une ressource lors du listage d'une collection.

Les opérateurs pris en charge sont :

* eq - Égalité
* lt/gt - Inférieur à/Supérieur à
* LTE/GTE - Inférieur ou égal à/Supérieur ou égal à


Exemple d'URL : « filter=field%20eq%20%27value%27 »

Exemples OpenAPI : « field eq 'value' »



| inclure | chaîne | requête | Faux  a| 
Indique les champs qui doivent être renvoyés lors de l’énumération d’une collection.

Exemples d'URL : « include=id », « include=id,name »

Exemples OpenAPI : « id »



| limite | chaîne | requête | Faux  a| 
Indique le nombre maximal de ressources à renvoyer lors de l’énumération d’une collection.

Exemples d'URL : « limit=2 »

Exemples OpenAPI : « 2 »



| Orderby | chaîne | requête | Faux  a| 
Indique l'ordre de tri des ressources lors de l'affichage d'une collection.

Exemples d'URL : « orderBy=name », « orderBy=name%20desc »

Exemples OpenAPI : « name desc »



| ignorer | chaîne | requête | Faux  a| 
Indique le nombre de ressources à ignorer lors de l'énumération d'une collection.

Exemples d'URL : « skip=1 »

Exemples OpenAPI : « 1 »

|===


== Réponse

[source]
----
Status: 200, Returns a JSON array of all matching resources in the collection. If individual fields are specified in the request, the items JSON array will contain the fields requested for each matching resource in the order specified.
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| articles | tableau[N'importe lequel de : link:#subscription_1_2_get_response_body["subscription_1.2_get_response_body"], tableau[]] | Vrai  a| 



| les métadonnées | link:#type_astra_metadata_list["type_astra_metadata_list"] | Vrai  a| 

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-subscriptions",
  "version": "1.2",
  "items": [
    {
      "type": "application/astra-subscription",
      "version": "1.1",
      "id": "d4c865c9-64a7-4661-ae4a-3307dffcd3da",
      "customerProfileID": "2157047189",
      "paymentProfileID": "E7CEB0A9F1BECA32A02493E1B31D5955",
      "paymentExpiry": "2022-02-01T00:00:00Z",
      "purchaseOrderNumber": "72384632",
      "marketplace": "netapp",
      "licenseSN": "278343",
      "terms": "trial",
      "status": "inactive",
      "appLimit": 0,
      "namespaceLimit": 10,
      "subscriptionPeriod": 90,
      "gracePeriod": 7,
      "reminderBeforePeriod": 30,
      "onboardStatus": "success",
      "costPerAppUnit": 0,
      "costPerNamespaceUnit": 0.005,
      "metadata": {
        "labels": [],
        "creationTimestamp": "2020-05-06T12:24:52.256624Z",
        "modificationTimestamp": "2020-05-06T12:24:52.256624Z",
        "createdBy": "11c0cfa1-4f27-4ef7-a21c-cb452fc5c9aa"
      }
    },
    {
      "type": "application/astra-subscription",
      "version": "1.1",
      "id": "4c43ed8b-078f-4fe3-b8c6-5d515f6382e6",
      "customerProfileID": "2157047189",
      "paymentProfileID": "E7CEB0A9F1BECA32A02493E1B31D5955",
      "paymentExpiry": "2022-05-01T00:00:00Z",
      "purchaseOrderNumber": "92374658",
      "marketplace": "netapp",
      "licenseSN": "374623",
      "terms": "paid",
      "status": "active",
      "appLimit": 0,
      "namespaceLimit": -1,
      "subscriptionPeriod": -1,
      "gracePeriod": -1,
      "reminderBeforePeriod": -1,
      "onboardStatus": "success",
      "costPerAppUnit": 0,
      "costPerNamespaceUnit": 0.005,
      "metadata": {
        "labels": [],
        "creationTimestamp": "2020-08-06T12:24:52.256624Z",
        "modificationTimestamp": "2020-08-06T12:24:52.256624Z",
        "createdBy": "11c0cfa1-4f27-4ef7-a21c-cb452fc5c9aa"
      }
    }
  ],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Réponse

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Réponse

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 



| invalidParams | tableau[link:#invalidParams["invalidParams"]] | Faux  a| 
Liste des paramètres de requête invalides

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Réponse

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Erreur

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 

|===
.Exemple de réponse d'erreur
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Définitions

.Voir les définitions
[%collapsible]
====
[role="api-collapsible-fifth-title"]
type_astra_label

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| nom | chaîne | Vrai  a| 



| valeur | chaîne | Vrai  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_update

Métadonnées spécifiques au client et au service associées à la ressource. Les valeurs définies sont :

* Conforme au schéma de métadonnées Astra. Si aucune étiquette n'est spécifiée lors de la création, un objet de métadonnées sera créé sans étiquette. Si aucune étiquette n'est spécifiée lors de la mise à jour, les étiquettes de l'objet de métadonnées, creationTimestamp et createdBy, seront conservées sans modification.


[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| étiquettes | tableau[link:#type_astra_label["type_astra_label"]] | Faux  a| 



| CréationTimestamp | chaîne | Faux  a| 



| ModificationTimestamp | chaîne | Faux  a| 



| CreatedBy | chaîne | Faux  a| 



| modifiedBy | chaîne | Faux  a| 

|===
[role="api-collapsible-fifth-title"]
subscription_1.2_get_response_body

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 
Type de média de la ressource. Les valeurs définies sont :

* "application/astra-subscription"




| version | chaîne | Vrai  a| 
Version de la ressource. Les valeurs définies sont :

* "1,0"
* "1,1"
* "1,2"




| id | chaîne | Vrai  a| 
Identifiant unique global de la ressource. Les valeurs définies sont :

* Conforme au schéma UUIDv4




| ID de profil client | chaîne | Vrai  a| 
La chaîne JSON contenant l’identifiant du profil client à partir de  http://authorize.net["Authorize.net"], qui a été invoqué par l’interface utilisateur, n’est pas définie pour le délai de grâce. Renvoie une chaîne vide lors de l’opération de lecture, si elle n’est pas définie. Les valeurs définies sont :

* Longueur minimale : 0
* Longueur maximale : 63




| ID de profil de paiement | chaîne | Faux  a| 
Chaîne JSON contenant l'identifiant du profil de paiement de http://Authorize.net["Authorize.net"] qui a été invoqué par l'interface utilisateur, non défini pour la période d'essai. Renvoie une chaîne vide lors de l'opération de lecture si non défini. Les valeurs définies sont :

* Longueur minimale : 0
* Longueur maximale : 63




| paymentExpiry | chaîne | Faux  a| 
Chaîne JSON contenant un horodatage indiquant la date d'expiration du mode de paiement. Cette information est obtenue auprès d'authorize.net(http://authorize.net[] et définie par l'interface utilisateur. Les valeurs possibles sont :

* Conforme au schéma de date et d'heure ISO-8601 Ce champ n'est pas renvoyé pour les périodes d'essai.




| purchaseOrderNumber | chaîne | Faux  a| 
Chaîne JSON contenant le numéro de bon de commande pour le mode de paiement. Les valeurs définies sont :

* Longueur minimale : 1
* Longueur maximale : 31




| marketplace | chaîne | Faux  a| 
Chaîne JSON indiquant la marketplace du compte sur laquelle les paiements seront enregistrés. Valeurs définies :

* "netapp"
* "azure"
* "aws"
* "gcp"




| licenseSN | chaîne | Faux  a| 
Chaîne JSON contenant le numéro de série de la licence pour le mode de paiement. Les valeurs définies sont :

* Longueur minimale : 1
* Longueur maximale : 31




| termes | chaîne | Vrai  a| 
Chaîne JSON indiquant le niveau actuel du compte. Les valeurs définies sont :

* "essai"
* "payé"




| statut | chaîne | Vrai  a| 
Chaîne JSON indiquant l'état actuel de l'abonnement. Les valeurs définies sont :

* "actif"
* "inactif"




| appLimit | nombre | Vrai  a| 
Numéro JSON indiquant la limite d'application pour cet abonnement. La valeur -1 indique l'absence de limite.



| namespaceLimit | nombre | Vrai  a| 
Numéro JSON indiquant la limite d'espace de noms pour cet abonnement. La valeur -1 indique l'absence de limite.



| subscriptionPeriod | nombre | Vrai  a| 
Nombre JSON indiquant la période d'abonnement. La valeur -1 indique une absence de limite. Unité : jours



| gracePeriod | nombre | Vrai  a| 
Numéro JSON indiquant le délai de grâce après l'expiration de l'abonnement d'essai ou l'annulation d'un abonnement payant. Unité : jours



| reminderBeforePeriod | nombre | Vrai  a| 
Nombre JSON indiquant le nombre de jours avant la fin de l'abonnement d'essai, à partir duquel les notifications client commenceront. La valeur est exprimée en jours avec une valeur de -1 indiquant que ce n'est pas applicable.



| onboardStatus | chaîne | Vrai  a| 
Chaîne JSON indiquant l'état actuel de l'onboarding client. Les valeurs valides sont "not started", "in progress", "success", "failed". Les valeurs définies sont :

* "non démarré"
* "en cours"
* "succès"
* "échoué"




| costPerAppUnit | nombre | Vrai  a| 
Nombre JSON indiquant le coût par unité d'application. Pour une version d'essai, la valeur est 0. Unité : US dollars



| costPerNamespaceUnit | nombre | Vrai  a| 
Nombre JSON indiquant le coût par unité d'espace de noms. Pour une version d'essai, la valeur est 0. Unité : US dollars



| les métadonnées | link:#type_astra_metadata_update["type_astra_metadata_update"] | Vrai  a| 
Métadonnées spécifiques au client et au service associées à la ressource. Les valeurs définies sont :

* Conforme au schéma de métadonnées Astra. Si aucune étiquette n'est spécifiée lors de la création, un objet de métadonnées sera créé sans étiquette. Si aucune étiquette n'est spécifiée lors de la mise à jour, les étiquettes de l'objet de métadonnées, creationTimestamp et createdBy, seront conservées sans modification.


|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_list

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| continuer | chaîne | Faux  a| 



| nombre | nombre | Faux  a| 



| étiquettes | tableau[link:#type_astra_label["type_astra_label"]] | Faux  a| 



| CréationTimestamp | chaîne | Faux  a| 



| ModificationTimestamp | chaîne | Faux  a| 



| CreatedBy | chaîne | Faux  a| 



| modifiedBy | chaîne | Faux  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| nom | chaîne | Vrai  a| 
Nom du paramètre de requête invalide



| raison | chaîne | Vrai  a| 
Raison pour laquelle le paramètre de requête est invalide

|===
====