---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-topology-v1-clusters-namespaces-.html 
summary: Récupérer un espace de noms pour un cluster 
---
= Récupérer un espace de noms pour un cluster
:allow-uri-read: 
:imagesdir: ../media/


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/topology/v1/clusters/{cluster_id}/namespaces/{namespace_id}`#

Renvoie la ressource d'API Namespace stockée dans le corps de la réponse JSON.



[[parameters]]
== Paramètres

[cols="5*"]
|===
| Nom | Type | Dans | Obligatoire | Description 


| identifiant_compte | chaîne | chemin | Vrai  a| 
ID de la ressource de compte conteneur

* exemple: {{.Account}}




| cluster_id | chaîne | chemin | Vrai  a| 
ID de la ressource de cluster contenant



| id_espace_de_noms | chaîne | chemin | Vrai  a| 
ID de la collection d'espaces de noms à lister

|===


[[response]]
== Réponse

[source]
----
Status: 200, Returns the stored Namespace API resource in the JSON response body.
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 
Type de média de la ressource. Les valeurs définies sont :

* "application/astra-namespace"




| version | chaîne | Vrai  a| 
Version de la ressource. Les valeurs définies sont :

* "1,0"
* "1,1"
* "1,2"




| id | chaîne | Vrai  a| 
Identifiant unique global de la ressource. Les valeurs définies sont :

* Conforme au schéma UUIDv4




| liens | tableau[link:#type_astra_link["type_astra_link"]] | Vrai  a| 
Liens décrivant les opérations prises en charge sur la ressource.



| nom | chaîne | Vrai  a| 
Chaîne JSON contenant une valeur indiquant le nom de l'espace de noms. Les valeurs définies sont :

* Longueur minimale : 1
* Longueur maximale : 255




| namespaceState | chaîne | Vrai  a| 
Chaîne JSON contenant une valeur indiquant l'état de l'espace de noms. Les valeurs définies sont :

* « découvert » - L'espace de noms a été trouvé dans le cluster
* « supprimé » - L'espace de noms a été supprimé du cluster, ou le cluster n'est pas géré mais il peut exister des ressources faisant référence à l'espace de noms




| namespaceStateDetails | tableau[link:#type_astra_stateDetail["type_astra_stateDetail"]] | Vrai  a| 
Tableau JSON d'objets JSON contenant des informations supplémentaires sur la raison de la transition de l'état « state » vers « state a », « state b » ou « state c ». Si aucune information n'est disponible, ce tableau sera vide. Valeurs possibles :

* Nombre minimum d’articles : 0




| kubernetesLabels | tableau[link:#type_astra_label["type_astra_label"]] | Faux  a| 
Tableau JSON d'objets JSON, chacun contenant une étiquette Kubernetes associée à l'espace de noms. Les valeurs définies sont :

* Conforme au schéma de tableau d'étiquettes Kubernetes




| kubernetesUID | chaîne | Vrai  a| 
Chaîne JSON contenant l'UID généré par Kubernetes de la ressource d'espace de noms



| clusterID | chaîne | Vrai  a| 
Chaîne JSON contenant un identifiant unique global du cluster dans lequel se trouve l'espace de noms. Les valeurs définies sont :

* Conforme au schéma d'identifiant Astra




| systemType | chaîne | Faux  a| 
Chaîne JSON indiquant que l'espace de noms est un type d'espace de noms système. Ce champ identifie le type d'espace de noms système, le cas échéant (version 1.1 uniquement). Valeurs définies :

* « kubernetes » - Un espace de noms système Kubernetes (K8s) générique, par exemple « kube-system »
* « netapp » - Un espace de noms système NetApp, par exemple « trident » ou « netapp-monitoring »
* « openshift » - Un espace de noms système OpenShift, par exemple, « openshift-monitoring »
* "rke" - Un espace de noms Rancher, par exemple "cattle-logging"
* « autres » - Espaces de noms système courants qui ne correspondent pas nécessairement à d'autres catégories, par exemple « ingress-nginx », « tekton-system »




| les métadonnées | link:#type_astra_metadata["type_astra_metadata"] | Vrai  a| 
Métadonnées spécifiques au client et au service associées à la ressource. Les valeurs définies sont :

* Conforme au schéma de métadonnées Astra


|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-namespace",
  "version": "1.2",
  "id": "214dc2eb-19a6-5444-b156-f4b6b551a81a",
  "links": [
    {
      "rel": "canonical",
      "href": "/accounts/0b311ae7-d89a-4a11-a52c-1349ca090415/topology/v1/namespaces/7d451d2f-196e-4234-aee9-7e2376047e63",
      "type": "application/vnd.netapp.astra.namespace"
    },
    {
      "rel": "collection",
      "href": "/accounts/0b311ae7-d89a-4a11-a52c-1349ca090415/topology/v1/clouds/e0490197-872e-4de8-9287-b04a938e801f/clusters/0f284377-e5dc-4dcd-bacd-3197f2b8a347/namespaces",
      "type": "application/vnd.netapp.astra.namespaces"
    }
  ],
  "name": "kube-system",
  "namespaceState": "discovered",
  "namespaceStateDetails": [
    {
      "type": "https://astra.netapp.io/stateDetails/9",
      "title": "Namespace Discovered",
      "detail": "The namespace was discovered in the indicated managed cluster"
    }
  ],
  "kubernetesLabels": [
    {
      "name": "app.kubernetes.io/environment",
      "value": "dev"
    }
  ],
  "clusterID": "0f284377-e5dc-4dcd-bacd-3197f2b8a347",
  "kubernetesUID": "4f28c377-e5dc-4dcd-b7cd-319cf2b8a345",
  "systemType": "kubernetes",
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


[[response]]
== Réponse

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


[[response]]
== Réponse

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 



| invalidParams | tableau[link:#invalidParams["invalidParams"]] | Faux  a| 
Liste des paramètres de requête invalides

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


[[response]]
== Réponse

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


[[error]]
== Erreur

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 

|===
.Exemple de réponse d'erreur
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


[[definitions]]
== Définitions

.Voir les définitions
[%collapsible]
====
[[targetSchema]]
[role="api-collapsible-fifth-title"]
targetSchema

[[accept-post]]
[role="api-collapsible-fifth-title"]
accept-post

[[accept-put]]
[role="api-collapsible-fifth-title"]
accepter-put

[[hints]]
[role="api-collapsible-fifth-title"]
indices

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| statut | chaîne | Faux  a| 



| permettre | tableau[chaîne] | Faux  a| 



| accept-post | link:#accept-post["accept-post"] | Faux  a| 



| autorisations | tableau[chaîne] | Faux  a| 



| accepter-put | link:#accept-put["accepter-put"] | Faux  a| 

|===
[[type_astra_link]]
[role="api-collapsible-fifth-title"]
type_astra_link

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| rel | chaîne | Vrai  a| 



| href | chaîne | Vrai  a| 



| type | chaîne | Faux  a| 



| targetSchema | link:#targetSchema["targetSchema"] | Faux  a| 



| titre | chaîne | Faux  a| 



| indices | link:#hints["indices"] | Faux  a| 

|===
[[additionalDetails]]
[role="api-collapsible-fifth-title"]
additionalDetails

[[type_astra_stateDetail]]
[role="api-collapsible-fifth-title"]
type_astra_stateDetail

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| additionalDetails | link:#additionalDetails["additionalDetails"] | Faux  a| 

|===
[[type_astra_label]]
[role="api-collapsible-fifth-title"]
type_astra_label

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| nom | chaîne | Vrai  a| 



| valeur | chaîne | Vrai  a| 

|===
[[type_astra_metadata]]
[role="api-collapsible-fifth-title"]
type_astra_metadata

Métadonnées spécifiques au client et au service associées à la ressource. Les valeurs définies sont :

* Conforme au schéma de métadonnées Astra


[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| étiquettes | tableau[link:#type_astra_label["type_astra_label"]] | Vrai  a| 



| CréationTimestamp | chaîne | Vrai  a| 



| ModificationTimestamp | chaîne | Vrai  a| 



| CreatedBy | chaîne | Vrai  a| 



| modifiedBy | chaîne | Faux  a| 

|===
[[invalidParams]]
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| nom | chaîne | Vrai  a| 
Nom du paramètre de requête invalide



| raison | chaîne | Vrai  a| 
Raison pour laquelle le paramètre de requête est invalide

|===
====