---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-topology-v1-managedclusters-storageclasses-.html 
summary: Récupérer une classe de stockage pour un cluster géré 
---
= Récupérer une classe de stockage pour un cluster géré
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/topology/v1/managedClusters/{managedCluster_id}/storageClasses/{storageClass_id}`#

Renvoie la ressource API de classe de stockage stockée dans le corps de la réponse JSON.



== Paramètres

[cols="5*"]
|===
| Nom | Type | Dans | Obligatoire | Description 


| identifiant_compte | chaîne | chemin | Vrai  a| 
ID de la ressource de compte conteneur

* exemple: {{.Account}}




| id_cluster_géré | chaîne | chemin | Vrai  a| 
ID de la ressource managedCluster conteneur



| storageClass_id | chaîne | chemin | Vrai  a| 
ID de la collection storageClass à lister

|===


== Réponse

[source]
----
Status: 200, Returns the stored Storage Class API resource in the JSON response body.
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 
Type de média de la ressource. Les valeurs définies sont :

* "application/astra-storageClass"




| version | chaîne | Vrai  a| 
Version de la ressource. Les valeurs définies sont :

* "1,0"
* "1,1"




| id | chaîne | Vrai  a| 
Identifiant unique global de la ressource. Les valeurs définies sont :

* Conforme au schéma UUIDv4




| nom | chaîne | Vrai  a| 
Chaîne JSON contenant une valeur indiquant le nom de la classe de stockage. Les valeurs définies sont :

* Longueur minimale : 1
* Longueur maximale : 255




| provisionneur | chaîne | Vrai  a| 
Chaîne JSON contenant une valeur indiquant le provisionneur associé à la classe de stockage. Les valeurs définies sont :

* Longueur minimale : 1
* Longueur maximale : 255




| disponible | chaîne | Vrai  a| 
Chaîne JSON indiquant si la classe de stockage est disponible pour le cluster ou est éligible pour être ajoutée au cluster lors de la gestion. Les valeurs définies sont :

* « disponible » - La classe de stockage est disponible pour utilisation
* « éligible » : la classe de stockage est éligible pour être utilisée par le cluster lorsqu’il est sous gestion
* « ineligible » - La classe de stockage ne peut pas être utilisée par le cluster lorsqu’elle est gérée.




| allowVolumeExpansion | chaîne | Vrai  a| 
Chaîne JSON indiquant si la classe de stockage autorise l'extension de volume. Les valeurs définies sont :

* « true » - La classe de stockage permet l'extension de volume
* « false » - La classe de stockage ne permet pas l’extension de volume
* « Indisponible » - On ignore si la classe de stockage permet l’extension de volume




| reclaimPolicy | chaîne | Vrai  a| 
Chaîne JSON contenant une valeur spécifique au cloud indiquant la politique de rétention de la classe de stockage. Les valeurs définies sont :

* Longueur minimale : 1
* Longueur maximale : 255




| volumeBindingMode | chaîne | Vrai  a| 
Chaîne JSON contenant une valeur spécifique au cloud indiquant le mode de liaison pour la classe de stockage. Les valeurs définies sont :

* Longueur minimale : 1
* Longueur maximale : 255




| isDefault | chaîne | Faux  a| 
Chaîne JSON indiquant si la classe de stockage contient l'annotation par défaut. Les valeurs définies sont :

* « true » - La classe de stockage contient l'annotation par défaut




| maxSnapshotCount | nombre | Faux  a| 
Numéro JSON indiquant le nombre d'instantanés pris en charge. Ces informations sont associées aux classes de stockage fournies par NetApp.



| maxBackupCount | nombre | Faux  a| 
Numéro JSON indiquant le nombre de sauvegardes prises en charge. Cette information est associée aux classes de stockage fournies par NetApp.



| prix | chaîne | Faux  a| 
Chaîne JSON indiquant les unités monétaires par unité de temps pour la classe de stockage. Ces informations sont associées aux classes de stockage fournies par NetApp. Les valeurs définies sont :

* Longueur minimale : 1
* Longueur maximale : 63




| devise | chaîne | Faux  a| 
Chaîne JSON indiquant le code ISO 4217 à trois lettres de la devise dans laquelle le prix est exprimé. Ces informations sont associées aux classes de stockage fournies par NetApp. Les valeurs définies sont :

* Longueur minimale : 1
* Longueur maximale : 255




| performance | nombre | Faux  a| 
Numéro JSON indiquant l'objectif de niveau de service (SLO) de performance en Mo/s. Ces informations sont associées aux classes de stockage fournies par NetApp.



| résilience | chaîne | Faux  a| 
Chaîne JSON indiquant la configuration de résilience du stockage. Ces informations sont associées aux classes de stockage fournies par NetApp. Les valeurs définies sont :

* « régional » - Le volume deviendra indisponible si une région donnée devient indisponible
* « multisite » - Le volume restera disponible si une région donnée devient indisponible




| les métadonnées | link:#type_astra_metadata["type_astra_metadata"] | Vrai  a| 
Métadonnées spécifiques au client et au service associées à la ressource. Les valeurs définies sont :

* Conforme au schéma de métadonnées Astra


|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-storageClass",
  "version": "1.1",
  "id": "ad9be22b-53c7-540c-8647-76afe2878952",
  "name": "my-storage-class",
  "provisioner": "csi.trident.netapp.io",
  "available": "eligible",
  "allowVolumeExpansion": "true",
  "reclaimPolicy": "recycle",
  "volumeBindingMode": "immediate",
  "isDefault": "true",
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Réponse

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Réponse

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 



| invalidParams | tableau[link:#invalidParams["invalidParams"]] | Faux  a| 
Liste des paramètres de requête invalides

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Réponse

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Erreur

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 

|===
.Exemple de réponse d'erreur
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Définitions

.Voir les définitions
[%collapsible]
====
[role="api-collapsible-fifth-title"]
type_astra_label

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| nom | chaîne | Vrai  a| 



| valeur | chaîne | Vrai  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadata

Métadonnées spécifiques au client et au service associées à la ressource. Les valeurs définies sont :

* Conforme au schéma de métadonnées Astra


[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| étiquettes | tableau[link:#type_astra_label["type_astra_label"]] | Vrai  a| 



| CréationTimestamp | chaîne | Vrai  a| 



| ModificationTimestamp | chaîne | Vrai  a| 



| CreatedBy | chaîne | Vrai  a| 



| modifiedBy | chaîne | Faux  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| nom | chaîne | Vrai  a| 
Nom du paramètre de requête invalide



| raison | chaîne | Vrai  a| 
Raison pour laquelle le paramètre de requête est invalide

|===
====