---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-core-v1-features.html 
summary: Lister toutes les fonctionnalités 
---
= Lister toutes les fonctionnalités
:allow-uri-read: 
:imagesdir: ../media/


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/features`#

Renvoie un tableau JSON contenant toutes les ressources correspondantes de la collection. Si des champs individuels sont spécifiés dans la requête, le tableau JSON items contiendra les champs demandés pour chaque ressource correspondante dans l'ordre indiqué.



[[parameters]]
== Paramètres

[cols="5*"]
|===
| Nom | Type | Dans | Obligatoire | Description 


| identifiant_compte | chaîne | chemin | Vrai  a| 
ID de la ressource de compte conteneur

* exemple: {{.Account}}




| inclure | chaîne | requête | Faux  a| 
Indique les champs qui doivent être renvoyés lors de l’énumération d’une collection.

Exemples d'URL : « include=id », « include=id,name »

Exemples OpenAPI : « id »



| limite | chaîne | requête | Faux  a| 
Indique le nombre maximal de ressources à renvoyer lors de l’énumération d’une collection.

Exemples d'URL : « limit=2 »

Exemples OpenAPI : « 2 »



| filtre | chaîne | requête | Faux  a| 
Indique les champs qui doivent être mis en correspondance pour renvoyer une ressource lors du listage d'une collection.

Les opérateurs pris en charge sont :

* eq - Égalité
* lt/gt - Inférieur à/Supérieur à
* LTE/GTE - Inférieur ou égal à/Supérieur ou égal à


Exemple d'URL : « filter=field%20eq%20%27value%27 »

Exemples OpenAPI : « field eq 'value' »



| nombre | chaîne | requête | Faux  a| 
Indique si le nombre total de ressources doit être renvoyé dans l'objet métadonnées.

Exemples d'URL : « count=true »

Exemples OpenAPI : "true"



| Orderby | chaîne | requête | Faux  a| 
Indique l'ordre de tri des ressources lors de l'affichage d'une collection.

Exemples d'URL : « orderBy=name », « orderBy=name%20desc »

Exemples OpenAPI : « name desc »



| ignorer | chaîne | requête | Faux  a| 
Indique le nombre de ressources à ignorer lors de l'énumération d'une collection.

Exemples d'URL : « skip=1 »

Exemples OpenAPI : « 1 »

|===


[[response]]
== Réponse

[source]
----
Status: 200, Returns a JSON array of all matching resources in the collection. If individual fields are specified in the request, the items JSON array will contain the fields requested for each matching resource in the order specified.
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| articles | tableau[N'importe lequel de : link:#feature_1_1_get_response_body["feature_1.1_get_response_body"], tableau[]] | Vrai  a| 



| les métadonnées | link:#type_astra_metadata_list["type_astra_metadata_list"] | Vrai  a| 

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-features",
  "version": "1.1",
  "items": [
    {
      "type": "application/astra-feature",
      "version": "1.0",
      "id": "c1d4d2f7-9b30-45a2-9657-8b24f17a4fd1",
      "name": "astra.account.rbac",
      "isEnabled": "true",
      "metadata": {
        "labels": [],
        "creationTimestamp": "2021-02-19T22:10:22.448274Z",
        "modificationTimestamp": "2021-02-19T22:10:22.448274Z",
        "createdBy": "c9550bbb-e70b-4578-8504-07397f875bcb"
      }
    },
    {
      "type": "application/astra-feature",
      "version": "1.0",
      "id": "85c693cd-2f89-4944-982a-e885301162bd",
      "name": "astra.account.smtp",
      "isEnabled": "false",
      "metadata": {
        "labels": [],
        "creationTimestamp": "2021-02-19T22:10:22.448274Z",
        "modificationTimestamp": "2021-02-19T22:10:22.448274Z",
        "createdBy": "c9550bbb-e70b-4578-8504-07397f875bcb"
      }
    }
  ],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


[[response]]
== Réponse

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


[[response]]
== Réponse

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 



| invalidParams | tableau[link:#invalidParams["invalidParams"]] | Faux  a| 
Liste des paramètres de requête invalides

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


[[response]]
== Réponse

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


[[response]]
== Réponse

[source]
----
Status: 503, Service unavailable
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/41",
  "title": "Service not ready",
  "detail": "Currently, the service can't respond to this request.",
  "status": "503"
}
----
====


[[error]]
== Erreur

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 

|===
.Exemple de réponse d'erreur
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


[[definitions]]
== Définitions

.Voir les définitions
[%collapsible]
====
[[type_astra_label]]
[role="api-collapsible-fifth-title"]
type_astra_label

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| nom | chaîne | Vrai  a| 



| valeur | chaîne | Vrai  a| 

|===
[[type_astra_metadata]]
[role="api-collapsible-fifth-title"]
type_astra_metadata

Métadonnées spécifiques au client et au service associées à la ressource. Les valeurs définies sont :

* Conforme au schéma de métadonnées Astra


[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| étiquettes | tableau[link:#type_astra_label["type_astra_label"]] | Vrai  a| 



| CréationTimestamp | chaîne | Vrai  a| 



| ModificationTimestamp | chaîne | Vrai  a| 



| CreatedBy | chaîne | Vrai  a| 



| modifiedBy | chaîne | Faux  a| 

|===
[[feature_1_1_get_response_body]]
[role="api-collapsible-fifth-title"]
feature_1.1_get_response_body

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 
Type de média de la ressource. Les valeurs définies sont :

* "application/astra-feature"




| version | chaîne | Vrai  a| 
Version de la ressource. Les valeurs définies sont :

* "1,0"
* "1,1"




| id | chaîne | Vrai  a| 
Identifiant unique global de la ressource. Les valeurs définies sont :

* Conforme au schéma UUIDv4




| nom | chaîne | Vrai  a| 
Chaîne JSON contenant un nom pour la fonctionnalité, au format hiérarchique pointé. Les valeurs définies sont :

* Longueur minimale : 1
* Longueur maximale : 63
* Cette chaîne de caractères est validée en interne afin de prévenir les attaques XSS, Unicode, de traversée de répertoire et d'injection SQL.




| isEnabled | chaîne | Vrai  a| 
Chaîne JSON contenant une valeur indiquant si l'indicateur de fonctionnalité est activé ou désactivé. Les valeurs définies sont :

* « true » - Le feature flag est activé.
* "false" - L'indicateur de fonctionnalité est désactivé.




| les métadonnées | link:#type_astra_metadata["type_astra_metadata"] | Vrai  a| 
Métadonnées spécifiques au client et au service associées à la ressource. Les valeurs définies sont :

* Conforme au schéma de métadonnées Astra


|===
[[type_astra_metadata_list]]
[role="api-collapsible-fifth-title"]
type_astra_metadata_list

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| continuer | chaîne | Faux  a| 



| nombre | nombre | Faux  a| 



| étiquettes | tableau[link:#type_astra_label["type_astra_label"]] | Faux  a| 



| CréationTimestamp | chaîne | Faux  a| 



| ModificationTimestamp | chaîne | Faux  a| 



| CreatedBy | chaîne | Faux  a| 



| modifiedBy | chaîne | Faux  a| 

|===
[[invalidParams]]
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| nom | chaîne | Vrai  a| 
Nom du paramètre de requête invalide



| raison | chaîne | Vrai  a| 
Raison pour laquelle le paramètre de requête est invalide

|===
====