---
sidebar: sidebar 
api: true 
explorer: true 
permalink: reference/get-accounts-topology-v1-appbackups-appassets.html 
summary: 'Lister les ressources de l"application pour une sauvegarde d"application' 
---
= Lister les ressources de l'application pour une sauvegarde d'application
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/topology/v1/appBackups/{appBackup_id}/appAssets`#

Renvoie un tableau JSON contenant toutes les ressources correspondantes de la collection. Si des champs individuels sont spécifiés dans la requête, le tableau JSON items contiendra les champs demandés pour chaque ressource correspondante dans l'ordre indiqué.



== Paramètres

[cols="5*"]
|===
| Nom | Type | Dans | Obligatoire | Description 


| identifiant_compte | chaîne | chemin | Vrai  a| 
ID de la ressource de compte conteneur

* exemple: {{.Account}}




| appBackup_id | chaîne | chemin | Vrai  a| 
ID de la ressource appBackup conteneur



| inclure | chaîne | requête | Faux  a| 
Indique les champs qui doivent être renvoyés lors de l’énumération d’une collection.

Exemples d'URL : « include=id », « include=id,name »

Exemples OpenAPI : « id »

* exemple : assetType,assetName




| limite | chaîne | requête | Faux  a| 
Indique le nombre maximal de ressources à renvoyer lors de l’énumération d’une collection.

Exemples d'URL : « limit=2 »

Exemples OpenAPI : « 2 »

|===


== Réponse

[source]
----
Status: 200, Returns a JSON array of all matching resources in the collection. If individual fields are specified in the request, the items JSON array will contain the fields requested for each matching resource in the order specified.
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| articles | tableau[N'importe lequel de : link:#appAsset_1_1_get_response_body["appAsset_1.1_get_response_body"], tableau[]] | Vrai  a| 



| les métadonnées | link:#type_astra_metadata_list["type_astra_metadata_list"] | Vrai  a| 

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-appAssets",
  "version": "1.1",
  "items": [
    [
      "Pod",
      "mediawiki-69c6fcf864-2wx6l"
    ],
    [
      "ReplicaSet",
      "mediawiki-69c6fcf864"
    ],
    [
      "Service",
      "mediawiki"
    ],
    [
      "Deployment",
      "mediawiki"
    ]
  ],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Réponse

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Réponse

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Réponse

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Erreur

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 

|===
.Exemple de réponse d'erreur
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Définitions

.Voir les définitions
[%collapsible]
====
[role="api-collapsible-fifth-title"]
GVK

Objet JSON contenant un groupe/une version/un type Kubernetes.

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| groupe | chaîne | Faux  a| 
Chaîne JSON contenant un identifiant de groupe attribué par Kubernetes. Les valeurs définies sont :

* Longueur minimale : 1
* Longueur maximale : 254




| type | chaîne | Faux  a| 
Chaîne JSON contenant un identifiant de type attribué par Kubernetes. Les valeurs définies sont :

* Longueur minimale : 1
* Longueur maximale : 254




| version | chaîne | Faux  a| 
Chaîne JSON contenant un identifiant de version attribué par Kubernetes. Les valeurs définies sont :

* Longueur minimale : 1
* Longueur maximale : 254


|===
[role="api-collapsible-fifth-title"]
type_json

Objet JSON contenant l'intégralité du contenu de la définition de ressource Kubernetes.

[role="api-collapsible-fifth-title"]
étiquettes

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| nom | chaîne | Vrai  a| 
Chaîne JSON contenant le nom de l'étiquette Les valeurs définies sont :

* Longueur minimale : 1
* Longueur maximale : 63
* L'expression régulière définie est : "^([\S.]{1,253}\/)?([a-z0-9A-Z_.-]){1,63}$"




| valeur | chaîne | Vrai  a| 
Chaîne JSON contenant la valeur de l'étiquette Defined values are :

* Longueur minimale : 1
* Longueur maximale : 63
* L'expression régulière définie est : "^([a-z0-9A-Z_.-]){1,63}$"


|===
[role="api-collapsible-fifth-title"]
type_astra_label

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| nom | chaîne | Vrai  a| 



| valeur | chaîne | Vrai  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadata

Métadonnées spécifiques au client et au service associées à la ressource. Les valeurs définies sont :

* Conforme au schéma de métadonnées Astra


[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| étiquettes | tableau[link:#type_astra_label["type_astra_label"]] | Vrai  a| 



| CréationTimestamp | chaîne | Vrai  a| 



| ModificationTimestamp | chaîne | Vrai  a| 



| CreatedBy | chaîne | Vrai  a| 



| modifiedBy | chaîne | Faux  a| 

|===
[role="api-collapsible-fifth-title"]
appAsset_1.1_get_response_body

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 
Type de média de la ressource. Les valeurs définies sont :

* "application/astra-appAsset"




| version | chaîne | Vrai  a| 
Version de la ressource. Les valeurs définies sont :

* "1,0"
* "1,1"




| id | chaîne | Vrai  a| 
Identifiant unique global de la ressource. Les valeurs définies sont :

* Conforme au schéma UUIDv4




| assetType | chaîne | Vrai  a| 
Chaîne JSON contenant une valeur indiquant le type de ressource décrite, obtenue depuis Kubernetes. Les valeurs définies sont :

* Longueur minimale : 1
* Longueur maximale : 254




| CréationTimestamp | chaîne | Vrai  a| 
Chaîne JSON contenant un horodatage indiquant la date de création des métadonnées Kubernetes. Les valeurs définies sont :

* Conforme au schéma de date et d'heure ISO-8601




| GVK | link:#GVK["GVK"] | Vrai  a| 
Objet JSON contenant un groupe/une version/un type Kubernetes.



| ressource | link:#type_json["type_json"] | Faux  a| 
Objet JSON contenant l'intégralité du contenu de la définition de ressource Kubernetes.



| identifiant de l'actif | chaîne | Vrai  a| 
Chaîne JSON contenant un identifiant attribué par Kubernetes. Les valeurs définies sont :

* Conforme au schéma d'identifiant Astra




| étiquettes | tableau[link:#labels["étiquettes"]] | Vrai  a| 
Tableau JSON d'objets JSON, chacun contenant une étiquette Kubernetes associée à la ressource. Si aucune information n'est disponible, ce tableau sera vide.

* Nombre minimum d’articles : 0




| assetName | chaîne | Vrai  a| 
Chaîne JSON contenant un nom attribué par Kubernetes. Les valeurs définies sont :

* Longueur minimale : 1
* Longueur maximale : 254




| espace de noms | chaîne | Faux  a| 
Chaîne JSON contenant un espace de noms attribué par Kubernetes. Les valeurs définies sont :

* Longueur minimale : 1
* Longueur maximale : 254




| les métadonnées | link:#type_astra_metadata["type_astra_metadata"] | Vrai  a| 
Métadonnées spécifiques au client et au service associées à la ressource. Les valeurs définies sont :

* Conforme au schéma de métadonnées Astra


|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_list

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| continuer | chaîne | Faux  a| 



| nombre | nombre | Faux  a| 



| étiquettes | tableau[link:#type_astra_label["type_astra_label"]] | Faux  a| 



| CréationTimestamp | chaîne | Faux  a| 



| ModificationTimestamp | chaîne | Faux  a| 



| CreatedBy | chaîne | Faux  a| 



| modifiedBy | chaîne | Faux  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| nom | chaîne | Vrai  a| 
Nom du paramètre de requête invalide



| raison | chaîne | Vrai  a| 
Raison pour laquelle le paramètre de requête est invalide

|===
====