---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-core-v1-packages.html 
summary: Lister tous les packages 
---
= Lister tous les packages
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/packages`#

Renvoie un tableau JSON contenant toutes les ressources correspondantes de la collection. Si des champs individuels sont spécifiés dans la requête, le tableau JSON items contiendra les champs demandés pour chaque ressource correspondante dans l'ordre indiqué.



== Paramètres

[cols="5*"]
|===
| Nom | Type | Dans | Obligatoire | Description 


| identifiant_compte | chaîne | chemin | Vrai  a| 
ID de la ressource de compte conteneur

* exemple: {{.Account}}




| filtre | chaîne | requête | Faux  a| 
Indique les champs qui doivent être mis en correspondance pour renvoyer une ressource lors du listage d'une collection.

Les opérateurs pris en charge sont :

* eq - Égalité
* lt/gt - Inférieur à/Supérieur à
* LTE/GTE - Inférieur ou égal à/Supérieur ou égal à


Exemple d'URL : « filter=field%20eq%20%27value%27 »

Exemples OpenAPI : « field eq 'value' »



| Orderby | chaîne | requête | Faux  a| 
Indique l'ordre de tri des ressources lors de l'affichage d'une collection.

Exemples d'URL : « orderBy=name », « orderBy=name%20desc »

Exemples OpenAPI : « name desc »



| inclure | chaîne | requête | Faux  a| 
Indique les champs qui doivent être renvoyés lors de l’énumération d’une collection.

Exemples d'URL : « include=id », « include=id,name »

Exemples OpenAPI : « id »

* exemple : id,packageName,packageVersion,softwareType




| limite | chaîne | requête | Faux  a| 
Indique le nombre maximal de ressources à renvoyer lors de l’énumération d’une collection.

Exemples d'URL : « limit=2 »

Exemples OpenAPI : « 2 »

|===


== Réponse

[source]
----
Status: 200, Returns a JSON array of all matching resources in the collection. If individual fields are specified in the request, the items JSON array will contain the fields requested for each matching resource in the order specified.
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| articles | tableau[N'importe lequel de : link:#package_1_0_get_response_body["package_1.0_get_response_body"], tableau[]] | Vrai  a| 



| les métadonnées | link:#type_astra_metadata_list["type_astra_metadata_list"] | Vrai  a| 

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-packages",
  "version": "1.0",
  "items": [
    [
      "e280ff62-be35-4f31-a31b-a210a1ad1b33",
      "acc",
      "22.01.0",
      "install"
    ],
    [
      "e8507dad-d33f-44b3-9c15-ec55ba6f6473",
      "acc",
      "22.01.1",
      "patch"
    ]
  ],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Réponse

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Réponse

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 



| invalidParams | tableau[link:#invalidParams["invalidParams"]] | Faux  a| 
Liste des paramètres de requête invalides

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Réponse

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Erreur

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 

|===
.Exemple de réponse d'erreur
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Définitions

.Voir les définitions
[%collapsible]
====
[role="api-collapsible-fifth-title"]
type_astra_stateTransition

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| depuis | chaîne | Vrai  a| 



| pour | tableau[chaîne] | Vrai  a| 

|===
[role="api-collapsible-fifth-title"]
additionalDetails

[role="api-collapsible-fifth-title"]
type_astra_stateDetail

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| additionalDetails | link:#additionalDetails["additionalDetails"] | Faux  a| 

|===
[role="api-collapsible-fifth-title"]
dependsOnImages

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| imagePath | chaîne | Vrai  a| 
Chaîne JSON contenant le chemin d'accès à cette image Docker. Elle ne doit pas contenir le nom du registre, uniquement le chemin absolu de la racine à l'image. Exemple : /globalcicd/acc Valeurs définies :

* Longueur minimale : 1
* Longueur maximale : 1023




| imageName | chaîne | Vrai  a| 
Chaîne JSON contenant le nom de l'image Docker. Les valeurs définies sont :

* Longueur minimale : 1
* Longueur maximale : 63




| imageTag | chaîne | Vrai  a| 
Chaîne JSON représentant l'étiquette/la version de cette image. Les valeurs définies sont :

* Longueur minimale : 1
* Longueur maximale : 31


|===
[role="api-collapsible-fifth-title"]
images

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| imageName | chaîne | Vrai  a| 
Chaîne JSON contenant le nom de l'image Docker. Les valeurs définies sont :

* Longueur minimale : 1
* Longueur maximale : 63




| imagePath | chaîne | Vrai  a| 
Chaîne JSON contenant le chemin d'accès à cette image Docker. Elle ne doit pas contenir le nom du registre, uniquement le chemin absolu de la racine à l'image. Exemple : /globalcicd/acc Valeurs définies :

* Longueur minimale : 1
* Longueur maximale : 1023




| imageTag | chaîne | Vrai  a| 
Chaîne JSON représentant l'étiquette/la version de cette image. Les valeurs définies sont :

* Longueur minimale : 1
* Longueur maximale : 31




| imageDigest | chaîne | Vrai  a| 
Chaîne JSON représentant le condensé de cette image. Les valeurs définies sont :

* L'expression régulière définie est : "^(sha256:)[0-9a-f]{64}$"




| dependsOnImages | tableau[link:#dependsOnImages["dependsOnImages"]] | Faux  a| 
Tableau JSON d'objets JSON décrivant les images nécessaires à l'installation ou à la mise à niveau de l'image actuelle.

|===
[role="api-collapsible-fifth-title"]
dependsOnComponents

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| componentName | chaîne | Vrai  a| 
Chaîne JSON décrivant le nom du composant. Les valeurs définies sont :

* "acc"
* "acs"
* "Trident"
* "kubernetes"




| versions | tableau[chaîne] | Vrai  a| 
Tableau JSON de chaînes JSON définissant la version du composant requise pour installer l'image actuelle.

|===
[role="api-collapsible-fifth-title"]
artefacts

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| artifactName | chaîne | Vrai  a| 
Chaîne JSON contenant le nom du fichier. Les valeurs définies sont :

* Longueur minimale : 1
* Longueur maximale : 63




| artifactIdentifier | chaîne | Vrai  a| 
Chaîne JSON contenant un identifiant pour ce fichier. Entre les versions d'un même type de package, le nom du fichier peut changer mais l'identifiant reste généralement le même. Les valeurs définies sont :

* Longueur minimale : 1
* Longueur maximale : 511




| artifactPath | chaîne | Vrai  a| 
Chaîne JSON contenant le chemin d'accès à cet artefact depuis la racine d'un emplacement/magasin de données Astra Control Center connu. Exemple : /vmware/1.0/ Les valeurs définies sont :

* Longueur minimale : 1
* Longueur maximale : 1023




| artifactVersion | chaîne | Faux  a| 
Chaîne JSON contenant la version de cet artefact, si elle est fournie. Les valeurs définies sont :

* Conforme au schéma SemVer
* Longueur minimale : 1
* Longueur maximale : 31




| dependsOnComponents | tableau[link:#dependsOnComponents["dependsOnComponents"]] | Faux  a| 
Tableau JSON d'objets JSON décrivant les composants installés nécessaires à l'installation/mise à niveau de l'image actuelle.

|===
[role="api-collapsible-fifth-title"]
fichiers

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| fileName | chaîne | Vrai  a| 
Chaîne JSON contenant le nom du fichier. Les valeurs définies sont :

* Longueur minimale : 1
* Longueur maximale : 63




| fileIdentifier | chaîne | Vrai  a| 
Chaîne JSON contenant l'identifiant de ce fichier. Entre les versions d'un même type de package, le nom du fichier peut changer mais l'identifiant reste généralement le même. Les valeurs définies sont :

* Longueur minimale : 1
* Longueur maximale : 511




| fileMediaType | chaîne | Vrai  a| 
Chaîne JSON contenant le type de média du fichier. Les valeurs définies correspondent à tout type de média défini par  https://www.iana.org/assignments/media-types/media-types.xhtml["IANA"]. De plus, application/x-yaml ou application/x-yaml pour les fichiers yaml est pris en charge.

* Longueur minimale : 1
* Longueur maximale : 211




| fileContents | chaîne | Vrai  a| 
Chaîne JSON contenant le contenu du fichier. Les valeurs définies sont :

* Conforme au schéma Base64 FIXME - Comment spécifier que ce format est compressé ? Quel algorithme, etc ?


|===
[role="api-collapsible-fifth-title"]
upgradableVersions

Objet JSON contenant les versions minimale et maximale pouvant être mises à niveau vers la version du package.

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| minVersion | chaîne | Faux  a| 
Chaîne JSON décrivant la version minimale pouvant être mise à niveau vers la version du package. Les valeurs définies sont :

* Conforme au schéma SemVer




| maxVersion | chaîne | Faux  a| 
Chaîne JSON décrivant la version maximale pouvant être mise à niveau vers la version du package. Les valeurs définies sont :

* Conforme au schéma SemVer


|===
[role="api-collapsible-fifth-title"]
dépendances

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| componentName | chaîne | Vrai  a| 
Chaîne JSON décrivant le nom du composant. Les valeurs définies sont :

* "acc"
* "acs"
* "Trident"
* "kubernetes"




| componentMinVersion | chaîne | Faux  a| 
Chaîne JSON décrivant la version minimale requise pour ce composant. Les valeurs définies sont :

* Conforme au schéma SemVer




| componentMaxVersion | chaîne | Faux  a| 
Chaîne JSON décrivant la version maximale requise pour ce composant. Les valeurs définies sont :

* Conforme au schéma SemVer


|===
[role="api-collapsible-fifth-title"]
type_astra_label

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| nom | chaîne | Vrai  a| 



| valeur | chaîne | Vrai  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadata

Métadonnées spécifiques au client et au service associées à la ressource. Les valeurs définies sont :

* Conforme au schéma de métadonnées Astra. Si aucune étiquette n'est spécifiée lors de la création, un objet de métadonnées sera créé sans étiquette.


[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| étiquettes | tableau[link:#type_astra_label["type_astra_label"]] | Vrai  a| 



| CréationTimestamp | chaîne | Vrai  a| 



| ModificationTimestamp | chaîne | Vrai  a| 



| CreatedBy | chaîne | Vrai  a| 



| modifiedBy | chaîne | Faux  a| 

|===
[role="api-collapsible-fifth-title"]
package_1.0_get_response_body

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 
Type de média de la ressource. Les valeurs définies sont :

* "application/astra-package"




| version | chaîne | Vrai  a| 
Version de la ressource. Les valeurs définies sont :

* "1,0"




| id | chaîne | Vrai  a| 
Identifiant unique global de la ressource. Les valeurs définies sont :

* Conforme au schéma UUIDv4




| packageName | chaîne | Vrai  a| 
Chaîne JSON contenant le nom du package. Les valeurs définies sont :

* Longueur minimale : 1
* Longueur maximale : 31 Exemples de valeurs :
* "acc"
* "acs"
* "Trident"




| packageVersion | chaîne | Vrai  a| 
Chaîne JSON contenant le SemVer du package. Les valeurs définies sont :

* Conforme au schéma SemVer




| packageType | chaîne | Vrai  a| 
Chaîne JSON contenant le type de package, indiquant s'il s'agit d'un package d'installation complet ou d'un correctif. Les valeurs définies sont :

* "installer"
* "correctif"




| bundleName | tableau[chaîne] | Faux  a| 
Tableau JSON de chaînes JSON contenant le nom du bundle dans lequel le package est contenu.



| severityLevel | chaîne | Vrai  a| 
Chaîne JSON décrivant le niveau de gravité de ce correctif ou de cette installation. Les valeurs définies sont :

* « recommended » - L'installation est recommandée - Valeur par défaut
* « Critique » - L'installation est fortement recommandée pour bénéficier des correctifs de bogues critiques et/ou des correctifs de sécurité




| packageState | chaîne | Vrai  a| 
Chaîne JSON contenant une valeur indiquant l'état opérationnel du package. Après vérification du package et après import, l'état indiquera « complete ». Sinon, l'état indiquera « incomplete ». Les valeurs définies sont :

* « Vérification en cours » - Le package est en cours de validation
* « corrupt » - Le package est corrompu
* « Incomplet » - Le package contient des éléments manquants
* « Disponible » - Tous les éléments associés au package sont disponibles et le package est prêt à être utilisé




| packageStateTransitions | tableau[link:#type_astra_stateTransition["type_astra_stateTransition"]] | Vrai  a| 
Tableau JSON d'objets JSON, chacun représentant l'ensemble des transitions d'état autorisées à partir d'un état défini. Chaque objet JSON contient les champs « from » et « to », où la valeur de « from » est le nom d'un état et la valeur de « to » est un tableau d'états de destination autorisés. Les valeurs définies sont :

* Conforme au schéma de transition d'état




| packageStateDetails | tableau[link:#type_astra_stateDetail["type_astra_stateDetail"]] | Vrai  a| 
Tableau JSON d'objets JSON répertoriant des détails supplémentaires sur l'« état » actuel. Si aucun détail n'est disponible, ce tableau sera vide.

* Nombre minimum d'articles : 0




| images | tableau[link:#images["images"]] | Faux  a| 
Tableau JSON d'objets JSON, chacun contenant une image Docker faisant partie du package.



| artefacts | tableau[link:#artifacts["artefacts"]] | Faux  a| 
Tableau JSON d'objets JSON décrivant les artefacts supplémentaires (binaires et autres) associés à ce package.



| fichiers | tableau[link:#files["fichiers"]] | Faux  a| 
Tableau JSON d'objets JSON, chacun représentant un artefact non image associé à ce package.



| upgradableVersions | link:#upgradableVersions["upgradableVersions"] | Faux  a| 
Objet JSON contenant les versions minimale et maximale pouvant être mises à niveau vers la version du package.



| dépendances | tableau[link:#dependencies["dépendances"]] | Faux  a| 
Tableau JSON d'objets JSON décrivant la version minimale d'une dépendance donnée requise pour que ce paquet puisse être installé



| les métadonnées | link:#type_astra_metadata["type_astra_metadata"] | Vrai  a| 
Métadonnées spécifiques au client et au service associées à la ressource. Les valeurs définies sont :

* Conforme au schéma de métadonnées Astra. Si aucune étiquette n'est spécifiée lors de la création, un objet de métadonnées sera créé sans étiquette.


|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_list

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| continuer | chaîne | Faux  a| 



| nombre | nombre | Faux  a| 



| étiquettes | tableau[link:#type_astra_label["type_astra_label"]] | Faux  a| 



| CréationTimestamp | chaîne | Faux  a| 



| ModificationTimestamp | chaîne | Faux  a| 



| CreatedBy | chaîne | Faux  a| 



| modifiedBy | chaîne | Faux  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| nom | chaîne | Vrai  a| 
Nom du paramètre de requête invalide



| raison | chaîne | Vrai  a| 
Raison pour laquelle le paramètre de requête est invalide

|===
====