---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-topology-v1-buckets.html 
summary: Lister tous les compartiments 
---
= Lister tous les compartiments
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/topology/v1/buckets`#

Renvoie un tableau JSON contenant toutes les ressources correspondantes de la collection. Si des champs individuels sont spécifiés dans la requête, le tableau JSON items contiendra les champs demandés pour chaque ressource correspondante dans l'ordre indiqué.



== Paramètres

[cols="5*"]
|===
| Nom | Type | Dans | Obligatoire | Description 


| identifiant_compte | chaîne | chemin | Vrai  a| 
ID de la ressource de compte conteneur

* exemple: {{.Account}}


|===


== Réponse

[source]
----
Status: 200, Returns a JSON array of all matching resources in the collection. If individual fields are specified in the request, the items JSON array will contain the fields requested for each matching resource in the order specified.
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| articles | tableau[N'importe lequel de : link:#bucket_1_2_get_response_body["bucket_1.2_get_response_body"], tableau[]] | Vrai  a| 



| les métadonnées | link:#type_astra_metadata_list["type_astra_metadata_list"] | Vrai  a| 

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-buckets",
  "version": "1.2",
  "items": [
    [
      "4c753e39-25e9-4b36-a8de-69f168aa59cd",
      "Test Bucket",
      "gcp"
    ],
    [
      "d8fd585d-6429-4c08-a308-af193a88eac7",
      "Local",
      "ontap-s3"
    ]
  ],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Réponse

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Réponse

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 



| invalidParams | tableau[link:#invalidParams["invalidParams"]] | Faux  a| 
Liste des paramètres de requête invalides

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Réponse

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Erreur

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 

|===
.Exemple de réponse d'erreur
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Définitions

.Voir les définitions
[%collapsible]
====
[role="api-collapsible-fifth-title"]
additionalDetails

[role="api-collapsible-fifth-title"]
type_astra_stateDetail

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| additionalDetails | link:#additionalDetails["additionalDetails"] | Faux  a| 

|===
[role="api-collapsible-fifth-title"]
s3

Objet JSON fournissant les paramètres du protocole Simple Storage Service (S3). (Utilisez cet objet pour tous les fournisseurs de type S3).

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| URL du serveur | chaîne | Vrai  a| 
Chaîne JSON contenant une URL vers le chemin de base du compartiment. Les valeurs définies sont :

* Longueur minimale : 0
* Longueur maximale : 1023




| bucketName | chaîne | Vrai  a| 
Chaîne JSON contenant le nom du compartiment S3. Les valeurs définies sont :

* Longueur minimale : 0
* Longueur maximale : 63


|===
[role="api-collapsible-fifth-title"]
gcp

Objet JSON fournissant les paramètres du protocole Google Cloud.

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| bucketName | chaîne | Vrai  a| 
Chaîne JSON contenant le nom du bucket Google Cloud sous-jacent. Les valeurs définies sont :

* Longueur minimale : 0
* Longueur maximale : 63


|===
[role="api-collapsible-fifth-title"]
azure

Objet JSON fournissant les paramètres du protocole Azure.

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| storageAccount | chaîne | Vrai  a| 
Chaîne JSON contenant le nom du compte de stockage Azure. Les valeurs définies sont :

* Longueur minimale : 0
* Longueur maximale : 63




| bucketName | chaîne | Vrai  a| 
Chaîne JSON contenant le nom du blob Azure sous-jacent. Les valeurs définies sont :

* Longueur minimale : 0
* Longueur maximale : 63


|===
[role="api-collapsible-fifth-title"]
bucketParameters

Objet JSON contenant les informations spécifiques au fournisseur de compartiment nécessaires pour accéder au compartiment. Les valeurs spécifiques de ce compartiment varient selon le fournisseur.

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| s3 | link:#s3["s3"] | Faux  a| 
Objet JSON fournissant les paramètres du protocole Simple Storage Service (S3). (Utilisez cet objet pour tous les fournisseurs de type S3).



| gcp | link:#gcp["gcp"] | Faux  a| 
Objet JSON fournissant les paramètres du protocole Google Cloud.



| azure | link:#azure["azure"] | Faux  a| 
Objet JSON fournissant les paramètres du protocole Azure.

|===
[role="api-collapsible-fifth-title"]
type_astra_label

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| nom | chaîne | Vrai  a| 



| valeur | chaîne | Vrai  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_update

Métadonnées spécifiques au client et au service associées à la ressource. Les valeurs définies sont :

* Conforme au schéma de métadonnées Astra. Si aucune étiquette n'est spécifiée lors de la création, un objet de métadonnées sera créé sans étiquette. Si aucune étiquette n'est spécifiée lors de la mise à jour, les étiquettes de l'objet de métadonnées, creationTimestamp et createdBy, seront conservées sans modification.


[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| étiquettes | tableau[link:#type_astra_label["type_astra_label"]] | Faux  a| 



| CréationTimestamp | chaîne | Faux  a| 



| ModificationTimestamp | chaîne | Faux  a| 



| CreatedBy | chaîne | Faux  a| 



| modifiedBy | chaîne | Faux  a| 

|===
[role="api-collapsible-fifth-title"]
bucket_1.2_get_response_body

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 
Type de média de la ressource. Les valeurs définies sont :

* "application/astra-bucket"




| version | chaîne | Vrai  a| 
Version de la ressource. Les valeurs définies sont :

* "1,0"
* "1,1"
* "1,2"




| id | chaîne | Vrai  a| 
Identifiant unique global de la ressource. Les valeurs définies sont :

* Conforme au schéma UUIDv4




| nom | chaîne | Vrai  a| 
Chaîne JSON contenant un nom attribué par l'utilisateur au compartiment. Les valeurs définies sont :

* Longueur minimale : 1
* Longueur maximale : 256




| identifiant | chaîne | Vrai  a| 
Chaîne JSON contenant l'identifiant des identifiants utilisés pour accéder au compartiment. Les valeurs définies sont :

* Conforme au schéma d'identifiant Astra




| État | chaîne | Vrai  a| 
Chaîne JSON contenant une valeur indiquant l'état opérationnel du compartiment. Les valeurs définies sont :

* « pending » - Le compartiment est programmé pour être découvert
* « disponible » - Le seau est disponible pour utilisation
* « défaillant » - Le bucket est dans un état de défaillance permanent
* « supprimé » - Le compartiment n'est actuellement pas accessible
* « unknown » - L'état du compartiment ne peut être déterminé




| stateDetails | tableau[link:#type_astra_stateDetail["type_astra_stateDetail"]] | Vrai  a| 
Tableau JSON d'objets JSON contenant des informations supplémentaires sur la raison pour laquelle « state » est passé à « removed » ou « failed ». Si aucun détail n'est disponible, ce tableau sera vide.

* Nombre minimum d’articles : 0




| retentionTime | nombre | Faux  a| 
Nombre de secondes représentant la durée de conservation d'un fichier sur ce compartiment. Les valeurs définies sont :

* -1 (Compartiment non pris en charge)
* 0 (Aucune politique de conservation connue)
* 
+
[quote]
____
0 (Politique de conservation connue)

____





| fournisseur | chaîne | Vrai  a| 
Chaîne JSON indiquant le protocole de compartiment pouvant être utilisé pour accéder au compartiment. Les valeurs définies sont :

* "ontap-s3"
* "storagegrid-s3"
* "generic-s3"
* "gcp"
* "azure"
* "aws"




| bucketParameters | link:#bucketParameters["bucketParameters"] | Vrai  a| 
Objet JSON contenant les informations spécifiques au fournisseur de compartiment nécessaires pour accéder au compartiment. Les valeurs spécifiques de ce compartiment varient selon le fournisseur.



| les métadonnées | link:#type_astra_metadata_update["type_astra_metadata_update"] | Vrai  a| 
Métadonnées spécifiques au client et au service associées à la ressource. Les valeurs définies sont :

* Conforme au schéma de métadonnées Astra. Si aucune étiquette n'est spécifiée lors de la création, un objet de métadonnées sera créé sans étiquette. Si aucune étiquette n'est spécifiée lors de la mise à jour, les étiquettes de l'objet de métadonnées, creationTimestamp et createdBy, seront conservées sans modification.


|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_list

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| continuer | chaîne | Faux  a| 



| nombre | nombre | Faux  a| 



| étiquettes | tableau[link:#type_astra_label["type_astra_label"]] | Faux  a| 



| CréationTimestamp | chaîne | Faux  a| 



| ModificationTimestamp | chaîne | Faux  a| 



| CreatedBy | chaîne | Faux  a| 



| modifiedBy | chaîne | Faux  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| nom | chaîne | Vrai  a| 
Nom du paramètre de requête invalide



| raison | chaîne | Vrai  a| 
Raison pour laquelle le paramètre de requête est invalide

|===
====