---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-topology-v1-storagebackends-volumes-.html 
summary: Récupérer un volume pour un backend de stockage 
---
= Récupérer un volume pour un backend de stockage
:allow-uri-read: 
:imagesdir: ../media/


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/topology/v1/storageBackends/{storageBackend_id}/volumes/{volume_id}`#

Renvoie la ressource API Volume stockée dans le corps de la réponse JSON.



[[parameters]]
== Paramètres

[cols="5*"]
|===
| Nom | Type | Dans | Obligatoire | Description 


| identifiant_compte | chaîne | chemin | Vrai  a| 
ID de la ressource de compte conteneur

* exemple: {{.Account}}




| storageBackend_id | chaîne | chemin | Vrai  a| 
ID de la ressource storageBackend conteneur



| volume_id | chaîne | chemin | Vrai  a| 
ID de la collection de volumes à lister

|===


[[response]]
== Réponse

[source]
----
Status: 200, Returns the stored Volume API resource in the JSON response body.
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 
Type de média de la ressource. Les valeurs définies sont :

* "application/astra-volume"




| version | chaîne | Vrai  a| 
Version de la ressource. Les valeurs définies sont :

* "1,0"
* "1,1"
* "1,2"




| id | chaîne | Vrai  a| 
Identifiant unique global de la ressource. Les valeurs définies sont :

* Conforme au schéma UUIDv4




| nom | chaîne | Vrai  a| 
Chaîne JSON contenant le nom du volume. Les valeurs définies sont :

* Longueur minimale : 1
* Longueur maximale : 255




| État | chaîne | Faux  a| 
Chaîne JSON contenant une valeur indiquant l'état opérationnel du volume.



| taille | chaîne | Faux  a| 
Chaîne JSON contenant la taille du volume.



| utilisé | nombre | Faux  a| 
Nombre JSON contenant le nombre d'octets de quota utilisés par le volume provisionné.



| usedPercentage | nombre | Faux  a| 
Nombre JSON contenant le pourcentage du volume utilisé.



| total | nombre | Faux  a| 
Nombre JSON contenant le total d'octets des volumes provisionnés.



| creationToken | chaîne | Faux  a| 
Chaîne JSON contenant le jeton de création du volume. Les valeurs définies sont :

* Longueur minimale : 1
* Longueur maximale : 255




| snapshotPossible | chaîne | Faux  a| 
Chaîne JSON indiquant si le pilote peut effectuer une capture instantanée du volume. Les valeurs définies sont :

* « true » - Le pilote peut prendre un instantané du volume
* « false » - Le pilote ne peut pas prendre un instantané du volume




| storageClass | chaîne | Faux  a| 
Chaîne JSON contenant la classe de stockage du volume.

* Les valeurs définies sont :
* Longueur minimale : 1
* Longueur maximale : 255




| pvcName | chaîne | Faux  a| 
Chaîne JSON contenant le nom PersistentVolumeClaim (PVC) du volume.

* Les valeurs définies sont :
* Longueur minimale : 1
* Longueur maximale : 255




| internalName | chaîne | Faux  a| 
Chaîne JSON contenant le nom interne du volume sur le cluster de stockage cible, s'il est disponible. Ce nom est obtenu à partir du pilote CSI de Kubernetes.

* Les valeurs définies sont :
* Longueur minimale : 1
* Longueur maximale : 255




| appsUsing | tableau[chaîne] | Vrai  a| 
Tableau JSON de chaînes JSON, chacune contenant l'ID d'une application utilisant le volume. Les valeurs définies sont :

* Conforme au schéma d'identifiant Astra




| ID du backend de stockage | chaîne | Faux  a| 
Chaîne JSON contenant l'identifiant du système de stockage qui fournit le volume. Les valeurs possibles sont :

* Conforme au schéma d'identifiant Astra




| orchestrateur | chaîne | Faux  a| 
Chaîne JSON contenant l'orchestrateur de ce volume. Ceci sera défini pour les volumes Astra Data Store. Les valeurs définies sont :

* "trident" - Trident a provisionné ce volume
* "vasa" - NetApp VASA Provider a provisionné ce volume
* « other » : le volume a été provisionné manuellement ou l’orchestrateur est inconnu




| serviceLevel | chaîne | Faux  a| 
Chaîne JSON contenant la politique de qualité de service (QoS) définie pour ce volume au niveau du backend de stockage. Ceci sera défini pour les volumes Astra Data Store.



| exportPolicy | chaîne | Faux  a| 
Chaîne JSON contenant la règle d'export associée à ce volume. Ceci sera défini pour les volumes Astra Data Store.



| nodeId | chaîne | Faux  a| 
Chaîne JSON contenant l'ID du nœud hébergeant le volume. Cette valeur sera définie pour les volumes Astra Data Store. Les valeurs définies sont :

* Conforme au schéma d'identifiant Astra




| healthState | chaîne | Faux  a| 
Chaîne JSON contenant une valeur indiquant l'état de santé du volume. Cette valeur sera définie pour les volumes Astra Data Store. Les valeurs définies sont :

* « Indéterminé » - L'état de la ressource ne peut être déterminé (par exemple, en raison d'un manque de connectivité)
* « Normal » - La ressource ne présente aucun problème connu et peut fournir des services conformément aux spécifications de l'interface
* « warning » : La ressource présente des problèmes connus qui ne l’empêchent pas de fournir des services conformément aux spécifications de l’interface.
* « critical » : La ressource présente des problèmes connus qui l’empêchent de fournir des services conformément aux spécifications de l’interface




| healthStateDetails | tableau[link:#type_astra_stateDetail["type_astra_stateDetail"]] | Vrai  a| 
Tableau JSON d'objets JSON répertoriant des informations supplémentaires sur l'état de santé actuel. Si aucun détail n'est disponible, ce tableau sera vide.

* Nombre minimum d'articles : 0




| les métadonnées | link:#type_astra_metadata["type_astra_metadata"] | Vrai  a| 
Métadonnées spécifiques au client et au service associées à la ressource. Les valeurs définies sont :

* Conforme au schéma de métadonnées Astra


|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-volume",
  "version": "1.2",
  "id": "ab5c9fb8-ddba-526f-8bd3-8d5b72cf4f7f",
  "name": "myVolume",
  "state": "ready",
  "size": "512 GiB",
  "used": 10000000000,
  "usedPercentage": 10,
  "total": 10000000000,
  "creationToken": "ba7d4e0c-6ae3-4b6e-859d-9463e7ca4b4e",
  "snapshotPossible": "true",
  "storageClass": "gold",
  "pvcName": "myVolume",
  "internalName": "trident_sd234234_23424_897d_876sd65w",
  "appsUsing": [],
  "orchestrator": "trident",
  "serviceLevel": "gold",
  "exportPolicy": "astra-vp-default",
  "nodeId": "94d16dd2-9beb-4edb-ab58-1a00e9a90052",
  "healthState": "normal",
  "healthStateDetails": [],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


[[response]]
== Réponse

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


[[response]]
== Réponse

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 



| invalidParams | tableau[link:#invalidParams["invalidParams"]] | Faux  a| 
Liste des paramètres de requête invalides

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


[[response]]
== Réponse

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


[[error]]
== Erreur

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 

|===
.Exemple de réponse d'erreur
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


[[definitions]]
== Définitions

.Voir les définitions
[%collapsible]
====
[[additionalDetails]]
[role="api-collapsible-fifth-title"]
additionalDetails

[[type_astra_stateDetail]]
[role="api-collapsible-fifth-title"]
type_astra_stateDetail

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| additionalDetails | link:#additionalDetails["additionalDetails"] | Faux  a| 

|===
[[type_astra_label]]
[role="api-collapsible-fifth-title"]
type_astra_label

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| nom | chaîne | Vrai  a| 



| valeur | chaîne | Vrai  a| 

|===
[[type_astra_metadata]]
[role="api-collapsible-fifth-title"]
type_astra_metadata

Métadonnées spécifiques au client et au service associées à la ressource. Les valeurs définies sont :

* Conforme au schéma de métadonnées Astra


[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| étiquettes | tableau[link:#type_astra_label["type_astra_label"]] | Vrai  a| 



| CréationTimestamp | chaîne | Vrai  a| 



| ModificationTimestamp | chaîne | Vrai  a| 



| CreatedBy | chaîne | Vrai  a| 



| modifiedBy | chaîne | Faux  a| 

|===
[[invalidParams]]
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| nom | chaîne | Vrai  a| 
Nom du paramètre de requête invalide



| raison | chaîne | Vrai  a| 
Raison pour laquelle le paramètre de requête est invalide

|===
====