---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-core-v1-settings.html 
summary: Afficher tous les paramètres 
---
= Afficher tous les paramètres
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/settings`#

Renvoie un tableau JSON contenant toutes les ressources correspondantes de la collection. Si des champs individuels sont spécifiés dans la requête, le tableau JSON items contiendra les champs demandés pour chaque ressource correspondante dans l'ordre indiqué.



== Paramètres

[cols="5*"]
|===
| Nom | Type | Dans | Obligatoire | Description 


| identifiant_compte | chaîne | chemin | Vrai  a| 
ID de la ressource de compte conteneur

* exemple: {{.Account}}




| inclure | chaîne | requête | Faux  a| 
Indique les champs qui doivent être renvoyés lors de l’énumération d’une collection.

Exemples d'URL : « include=id », « include=id,name »

Exemples OpenAPI : « id »



| limite | chaîne | requête | Faux  a| 
Indique le nombre maximal de ressources à renvoyer lors de l’énumération d’une collection.

Exemples d'URL : « limit=2 »

Exemples OpenAPI : « 2 »



| filtre | chaîne | requête | Faux  a| 
Indique les champs qui doivent être mis en correspondance pour renvoyer une ressource lors du listage d'une collection.

Les opérateurs pris en charge sont :

* eq - Égalité
* lt/gt - Inférieur à/Supérieur à
* LTE/GTE - Inférieur ou égal à/Supérieur ou égal à


Exemple d'URL : « filter=field%20eq%20%27value%27 »

Exemples OpenAPI : « field eq 'value' »



| nombre | chaîne | requête | Faux  a| 
Indique si le nombre total de ressources doit être renvoyé dans l'objet métadonnées.

Exemples d'URL : « count=true »

Exemples OpenAPI : "true"



| Orderby | chaîne | requête | Faux  a| 
Indique l'ordre de tri des ressources lors de l'affichage d'une collection.

Exemples d'URL : « orderBy=name », « orderBy=name%20desc »

Exemples OpenAPI : « name desc »



| ignorer | chaîne | requête | Faux  a| 
Indique le nombre de ressources à ignorer lors de l'énumération d'une collection.

Exemples d'URL : « skip=1 »

Exemples OpenAPI : « 1 »

|===


== Réponse

[source]
----
Status: 200, Returns a JSON array of all matching resources in the collection. If individual fields are specified in the request, the items JSON array will contain the fields requested for each matching resource in the order specified.
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| articles | tableau[N'importe lequel de : link:#setting_1_1_get_response_body["setting_1.1_get_response_body"], tableau[]] | Vrai  a| 



| les métadonnées | link:#type_astra_metadata_list["type_astra_metadata_list"] | Vrai  a| 

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-settings",
  "version": "1.1",
  "items": [
    {
      "type": "application/astra-setting",
      "version": "1.0",
      "id": "5da0a2ed-c51d-4d91-8b98-ed3aa8a88cc5",
      "name": "astra.account.smtp",
      "currentConfig": {
        "credential": "",
        "isEnabled": "false",
        "port": 587,
        "relayServer": "smtp.sendgrid.net"
      },
      "configSchema": {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "title": "astra.account.smtp",
        "type": "object",
        "properties": {
          "credential": {
            "type": "string",
            "description": "The credential ID for SMTP authentication."
          },
          "isEnabled": {
            "type": "string",
            "description": "This property determines if this setting is enabled or not."
          },
          "port": {
            "type": "integer",
            "description": "The SMTP port. For an unencrypted or a TLS connection, use port 25, 2525, or 587."
          },
          "relayServer": {
            "type": "string",
            "description": "This setting is sometimes referred to as the external SMTP server or the SMTP relay."
          }
        },
        "additionalProperties": false,
        "required": [
          "relayServer",
          "port",
          "isEnabled"
        ]
      },
      "state": "valid",
      "stateUnready": [],
      "metadata": {
        "labels": [],
        "creationTimestamp": "2021-06-04T20:14:52Z",
        "modificationTimestamp": "2021-06-04T20:14:52Z",
        "createdBy": "c9550bbb-e70b-4578-8504-07397f875bcb",
        "modifiedBy": "65e1571b-1b46-4f05-95b0-7d7f5a93da6a"
      }
    }
  ],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Réponse

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Réponse

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 



| invalidParams | tableau[link:#invalidParams["invalidParams"]] | Faux  a| 
Liste des paramètres de requête invalides

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Réponse

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Réponse

[source]
----
Status: 503, Service unavailable
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/41",
  "title": "Service not ready",
  "detail": "Currently, the service can't respond to this request.",
  "status": "503"
}
----
====


== Erreur

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 

|===
.Exemple de réponse d'erreur
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Définitions

.Voir les définitions
[%collapsible]
====
[role="api-collapsible-fifth-title"]
type_json

Objet JSON contenant les clés et les valeurs qui constituent la configuration actuelle de ce paramètre. Le contenu de cet objet doit être conforme au schéma JSON contenu dans le champ configSchema. Les valeurs par défaut sont fournies par le configmap. Après modification des valeurs par défaut par l'utilisateur, elles ne seront pas écrasées.

[role="api-collapsible-fifth-title"]
type_json

Objet JSON contenant les clés et les valeurs qui composent la configuration demandée pour ce paramètre. Le contenu de cet objet doit être conforme au schéma JSON contenu dans le champ configSchema. L'objet n'existe pas tant qu'il n'est pas spécifié. Lorsqu'il est spécifié, cela déclenche le service de fonctionnalités pour notifier le service correspondant afin de demander que la configuration souhaitée puisse être appliquée. Le service correspondant peut alors effectuer la validation et appliquer la configuration souhaitée à la configuration actuelle.

[role="api-collapsible-fifth-title"]
propriétés

[role="api-collapsible-fifth-title"]
type_json_schema

Objet JSON contenant le schéma JSON de la propriété config dans cette ressource. Doit être conforme au brouillon 7 du schéma JSON. Si des valeurs de config sont présentes dans la ressource, la validation par rapport au configSchema indiqué est obligatoire. Par convention courante, il est recommandé que les configurations comportent un champ « isEnabled », lorsque cela est approprié. Le champ « isEnabled » contient une valeur indiquant si le paramètre est activé (« true ») ou désactivé (« false »).

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| $schema | chaîne | Vrai  a| 



| type | chaîne | Vrai  a| 



| propriétés | link:#properties["propriétés"] | Vrai  a| 



| additionalProperties | booléen | Vrai  a| 



| requis | tableau[chaîne] | Vrai  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_label

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| nom | chaîne | Vrai  a| 



| valeur | chaîne | Vrai  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_update

Métadonnées spécifiques au client et au service associées à la ressource. Les valeurs définies sont :

* Conforme au schéma de métadonnées Astra. Si non spécifié lors de la mise à jour, les étiquettes de l'objet de métadonnées, creationTimestamp et createdBy, seront conservées sans modification.


[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| étiquettes | tableau[link:#type_astra_label["type_astra_label"]] | Faux  a| 



| CréationTimestamp | chaîne | Faux  a| 



| ModificationTimestamp | chaîne | Faux  a| 



| CreatedBy | chaîne | Faux  a| 



| modifiedBy | chaîne | Faux  a| 

|===
[role="api-collapsible-fifth-title"]
setting_1.1_get_response_body

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 
Type de média de la ressource. Les valeurs définies sont :

* "application/astra-setting"




| version | chaîne | Vrai  a| 
Version de la ressource. Les valeurs définies sont :

* "1,0"
* "1,1"




| id | chaîne | Vrai  a| 
Identifiant unique global de la ressource. Les valeurs définies sont :

* Conforme au schéma UUIDv4




| nom | chaîne | Vrai  a| 
Chaîne JSON contenant le nom du paramètre, au format hiérarchique pointé (.). Les valeurs définies sont :

* Longueur minimale : 1
* Longueur maximale : 63
* Cette chaîne de caractères est validée en interne afin de prévenir les attaques XSS, Unicode, de traversée de répertoires et d'injection SQL. Cette valeur est définie par la configmap chargée à l'exécution et ne peut pas être modifiée par l'utilisateur.




| currentConfig | link:#type_json["type_json"] | Vrai  a| 
Objet JSON contenant les clés et les valeurs qui constituent la configuration actuelle de ce paramètre. Le contenu de cet objet doit être conforme au schéma JSON contenu dans le champ configSchema. Les valeurs par défaut sont fournies par le configmap. Après modification des valeurs par défaut par l'utilisateur, elles ne seront pas écrasées.



| desiredConfig | link:#type_json["type_json"] | Faux  a| 
Objet JSON contenant les clés et les valeurs qui composent la configuration demandée pour ce paramètre. Le contenu de cet objet doit être conforme au schéma JSON contenu dans le champ configSchema. L'objet n'existe pas tant qu'il n'est pas spécifié. Lorsqu'il est spécifié, cela déclenche le service de fonctionnalités pour notifier le service correspondant afin de demander que la configuration souhaitée puisse être appliquée. Le service correspondant peut alors effectuer la validation et appliquer la configuration souhaitée à la configuration actuelle.



| configSchema | link:#type_json_schema["type_json_schema"] | Vrai  a| 
Objet JSON contenant le schéma JSON de la propriété config dans cette ressource. Doit être conforme au brouillon 7 du schéma JSON. Si des valeurs de config sont présentes dans la ressource, la validation par rapport au configSchema indiqué est obligatoire. Par convention courante, il est recommandé que les configurations comportent un champ « isEnabled », lorsque cela est approprié. Le champ « isEnabled » contient une valeur indiquant si le paramètre est activé (« true ») ou désactivé (« false »).



| État | chaîne | Vrai  a| 
Chaîne JSON contenant une valeur indiquant l'état opérationnel de l'application. Les valeurs définies sont :

* « valide » - La configuration actuelle correspond à la configuration souhaitée.
* « En attente » - La configuration souhaitée est en cours d'application.
* "erreur" - La configuration souhaitée ne peut pas être appliquée.




| stateUnready | tableau[chaîne] | Vrai  a| 
Tableau JSON de chaînes JSON, chacune indiquant une raison pour laquelle le paramètre n'a pas pu être appliqué. Les valeurs définies sont :

* Longueur minimale : 1
* Longueur maximale : 127




| les métadonnées | link:#type_astra_metadata_update["type_astra_metadata_update"] | Vrai  a| 
Métadonnées spécifiques au client et au service associées à la ressource. Les valeurs définies sont :

* Conforme au schéma de métadonnées Astra. Si non spécifié lors de la mise à jour, les étiquettes de l'objet de métadonnées, creationTimestamp et createdBy, seront conservées sans modification.


|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_list

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| continuer | chaîne | Faux  a| 



| nombre | nombre | Faux  a| 



| étiquettes | tableau[link:#type_astra_label["type_astra_label"]] | Faux  a| 



| CréationTimestamp | chaîne | Faux  a| 



| ModificationTimestamp | chaîne | Faux  a| 



| CreatedBy | chaîne | Faux  a| 



| modifiedBy | chaîne | Faux  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| nom | chaîne | Vrai  a| 
Nom du paramètre de requête invalide



| raison | chaîne | Vrai  a| 
Raison pour laquelle le paramètre de requête est invalide

|===
====