---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-k8s-v1-apps-executionhooks-.html 
summary: 'Récupérer un hook d"exécution pour une application' 
---
= Récupérer un hook d'exécution pour une application
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/k8s/v1/apps/{app_id}/executionHooks/{executionHook_id}`#

Renvoie la ressource d'API Execution Hook stockée dans le corps de la réponse JSON. Renseigne également matchingContainers et matchingImages en fonction du matchingCriteria actuel et de l'application définie.



== Paramètres

[cols="5*"]
|===
| Nom | Type | Dans | Obligatoire | Description 


| identifiant_compte | chaîne | chemin | Vrai  a| 
ID de la ressource de compte conteneur

* exemple: {{.Account}}




| app_id | chaîne | chemin | Vrai  a| 
ID de la ressource d'application contenant



| executionHook_id | chaîne | chemin | Vrai  a| 
ID de la executionHook collection à lister

|===


== Réponse

[source]
----
Status: 200, Returns the stored Execution Hook API resource in the JSON response body. Also populates matchingContainers and matchingImages based on the current matchingCriteria and the defined app.
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 
Type de média de la ressource. Les valeurs définies sont :

* "application/astra-executionHook"




| version | chaîne | Vrai  a| 
Version de la ressource. Les valeurs définies sont :

* "1,0"
* "1,1"
* "1,2"
* "1,3"




| id | chaîne | Vrai  a| 
Identifiant unique global de la ressource. Les valeurs définies sont :

* Conforme au schéma UUIDv4




| nom | chaîne | Vrai  a| 
Chaîne JSON contenant un nom spécifié par l'utilisateur pour la ressource. Les valeurs définies sont :

* Longueur minimale : 1
* Longueur maximale : 63 Le nom doit être unique pour toutes les ressources de hook d’exécution.




| hookType | chaîne | Vrai  a| 
Chaîne JSON définissant le type de hook. Les valeurs définies sont :

* "netapp" - Hook d'exécution fourni par NetApp.
* « custom » - lié à un ID d’application spécifique. Les ressources du hook d’exécution avec hookType « netapp » sont en lecture seule.




| matchingCriteria | tableau[link:#matchingCriteria["matchingCriteria"]] | Vrai  a| 
Tableau JSON d'objets JSON décrivant les critères de correspondance pour le hook d'exécution. Lorsque plusieurs matchingCriteria sont spécifiés, un ET logique est appliqué aux critères. Les valeurs définies sont :

* Nombre minimum d’articles : 0
* Nombre maximum d'articles : 10




| matchingContainers | tableau[link:#matchingContainers["matchingContainers"]] | Faux  a| 
Tableau JSON d'objets JSON pour chaque conteneur correspondant aux critères de correspondance configurés au sein de l'application définie.



| matchingImages | tableau[chaîne] | Faux  a| 
Tableau JSON de chaînes JSON pour les images conteneurs correspondantes. Les valeurs définies sont :

* Nombre minimum d’articles : 0
* Nombre maximum d’éléments : 4095
* Longueur minimale : 1
* Longueur maximale : 255




| action | chaîne | Vrai  a| 
Chaîne JSON indiquant l'action que le hook d'exécution lancera si les critères de correspondance sont remplis. Les valeurs définies sont :

* "instantané"
* "sauvegarde"
* "restaurer"
* « basculement »




| scène | chaîne | Vrai  a| 
Chaîne JSON indiquant l'étape de l'action à laquelle le hook sera exécuté. Les valeurs définies sont :

* "pre" - Le hook d'exécution sera exécuté avant l'action spécifiée.
* « post » : le hook d’exécution sera lancé après l’action spécifiée. Les valeurs pour l’action « snapshot » sont « pre » et « post ». Les valeurs pour l’action « backup » sont « pre » et « post ». La valeur pour l’action « restore » est « post ». La valeur pour l’action « failover » est « post ».




| hookSourceID | chaîne | Vrai  a| 
Chaîne JSON contenant l'identifiant de la source du hook exécuté par ce hook. Les valeurs définies sont :

* Conforme au schéma d'identifiant Astra




| arguments | tableau[chaîne] | Faux  a| 
Tableau JSON de chaînes JSON pour les arguments de la source. Les valeurs définies sont :

* Nombre minimum d’articles : 0
* Nombre maximum d'articles : 16
* Longueur minimale : 0
* Longueur maximale : 127




| ID de l'application | chaîne | Faux  a| 
Chaîne JSON contenant l'identifiant associé de l'application à laquelle ce hook est lié. En essence, d'autres critères de correspondance, si définis. Les valeurs définies sont :

* Conforme au schéma d'identifiant Astra




| activé | chaîne | Vrai  a| 
Chaîne JSON indiquant si le hook d'exécution est activé. Les valeurs possibles sont :

* "true" - Le hook d'exécution est activé et sera exécuté comme spécifié.
* « false » - Le hook d’exécution est désactivé et ne sera jamais exécuté. La valeur par défaut est « true ».




| description | chaîne | Faux  a| 
Chaîne JSON contenant une description, spécifiée par l'utilisateur, de la source du hook. Les valeurs définies sont :

* Longueur minimale : 0
* Longueur maximale : 511




| les métadonnées | link:#type_astra_metadata_update["type_astra_metadata_update"] | Vrai  a| 
Métadonnées spécifiques au client et au service associées à la ressource. Les valeurs définies sont :

* Conforme au schéma de métadonnées Astra. Si aucune étiquette n'est spécifiée lors de la création, un objet de métadonnées sera créé sans étiquette. Si aucune étiquette n'est spécifiée lors de la mise à jour, les étiquettes de l'objet de métadonnées, creationTimestamp et createdBy, seront conservées sans modification.


|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-executionHook",
  "version": "1.3",
  "id": "5f7e2e31-280d-5984-a28b-2d19ab5b77c0",
  "name": "Payroll",
  "hookType": "custom",
  "matchingCriteria": [
    {
      "type": "podLabel",
      "value": "^env=production$"
    },
    {
      "type": "containerName",
      "value": "^payroll-master"
    }
  ],
  "matchingImages": [
    "docker.io/bitnami/payroll:3.7.8",
    "docker.io/bitnami/payroll:4.1.2"
  ],
  "matchingContainers": [
    {
      "namespaceName": "payroll-east",
      "podName": "payroll-release3-7",
      "podLabels": [
        {
          "name": "env",
          "value": "production"
        },
        {
          "name": "app.kubernetes.io/managed-by",
          "value": "Helm"
        }
      ],
      "containerName": "payroll-master-0",
      "containerImage": "docker.io/bitnami/payroll:3.7.8"
    },
    {
      "namespaceName": "payroll-east",
      "podName": "payroll-release3-7",
      "podLabels": [
        {
          "name": "env",
          "value": "production"
        },
        {
          "name": "app.kubernetes.io/managed-by",
          "value": "Helm"
        }
      ],
      "containerName": "payroll-master-1",
      "containerImage": "docker.io/bitnami/payroll:3.7.8"
    }
  ],
  "action": "snapshot",
  "stage": "pre",
  "hookSourceID": "50e89023-ba84-435d-bb47-1833f4c250ff",
  "arguments": [
    "freeze"
  ],
  "appID": "7be5ae7c-151d-4230-ac39-ac1d0b33c2a9",
  "enabled": "true",
  "description": "Payroll production hook",
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Réponse

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Réponse

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 



| invalidParams | tableau[link:#invalidParams["invalidParams"]] | Faux  a| 
Liste des paramètres de requête invalides

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Réponse

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Erreur

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 

|===
.Exemple de réponse d'erreur
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Définitions

.Voir les définitions
[%collapsible]
====
[role="api-collapsible-fifth-title"]
matchingCriteria

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 
Chaîne JSON identifiant le type de critères de correspondance.



| valeur | chaîne | Vrai  a| 
Chaîne JSON contenant une expression régulière permettant de rechercher le type de correspondance spécifié. Syntaxe de l'expression régulière : https://github.com/google/re2/wiki/Syntax[]

|===
[role="api-collapsible-fifth-title"]
type_k8s_label

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| nom | chaîne | Vrai  a| 



| valeur | chaîne | Vrai  a| 

|===
[role="api-collapsible-fifth-title"]
matchingContainers

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| podName | chaîne | Faux  a| 
Chaîne JSON du nom du pod correspondant au conteneur.



| podLabels | tableau[link:#type_k8s_label["type_k8s_label"]] | Faux  a| 
Tableau JSON d'objets d'étiquette correspondant aux étiquettes du pod du conteneur correspondant.



| containerImage | chaîne | Faux  a| 
Chaîne JSON de l'image du conteneur correspondant.



| containerName | chaîne | Faux  a| 
Chaîne JSON du nom du conteneur correspondant.



| namespaceName | chaîne | Faux  a| 
Chaîne JSON correspondant au nom de l'espace de noms du pod du conteneur.

|===
[role="api-collapsible-fifth-title"]
type_astra_label

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| nom | chaîne | Vrai  a| 



| valeur | chaîne | Vrai  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_update

Métadonnées spécifiques au client et au service associées à la ressource. Les valeurs définies sont :

* Conforme au schéma de métadonnées Astra. Si aucune étiquette n'est spécifiée lors de la création, un objet de métadonnées sera créé sans étiquette. Si aucune étiquette n'est spécifiée lors de la mise à jour, les étiquettes de l'objet de métadonnées, creationTimestamp et createdBy, seront conservées sans modification.


[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| étiquettes | tableau[link:#type_astra_label["type_astra_label"]] | Faux  a| 



| CréationTimestamp | chaîne | Faux  a| 



| ModificationTimestamp | chaîne | Faux  a| 



| CreatedBy | chaîne | Faux  a| 



| modifiedBy | chaîne | Faux  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| nom | chaîne | Vrai  a| 
Nom du paramètre de requête invalide



| raison | chaîne | Vrai  a| 
Raison pour laquelle le paramètre de requête est invalide

|===
====