---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-topology-v1-clouds-.html 
summary: Récupérer un cloud 
---
= Récupérer un cloud
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/topology/v1/clouds/{cloud_id}`#

Renvoie la ressource Cloud API stockée dans le corps de la réponse JSON.



== Paramètres

[cols="5*"]
|===
| Nom | Type | Dans | Obligatoire | Description 


| identifiant_compte | chaîne | chemin | Vrai  a| 
ID de la ressource de compte conteneur

* exemple: {{.Account}}




| cloud_id | chaîne | chemin | Vrai  a| 
ID de la collection cloud à lister

|===


== Réponse

[source]
----
Status: 200, Returns the stored Cloud API resource in the JSON response body.
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 
Type de média de la ressource. Les valeurs définies sont :

* "application/astra-cloud"




| version | chaîne | Vrai  a| 
Version de la ressource. Les valeurs définies sont :

* "1,0"
* "1,1"




| id | chaîne | Vrai  a| 
Identifiant unique global de la ressource. Les valeurs définies sont :

* Conforme au schéma UUIDv4




| nom | chaîne | Vrai  a| 
Chaîne JSON contenant le nom du cloud. Les valeurs définies sont :

* Longueur minimale : 1
* Longueur maximale : 63
* Cette chaîne de caractères est validée en interne afin de prévenir les attaques XSS, Unicode, de traversée de répertoire et d'injection SQL




| État | chaîne | Vrai  a| 
Chaîne JSON contenant une valeur indiquant l'état opérationnel du cloud. Les valeurs définies sont :

* « En attente » - Le cloud est programmé pour être découvert
* « découverte » – Le cloud est en cours de découverte
* « Provisionnement » - Le cloud est en cours de provisionnement
* « running » - Le cloud fonctionne normalement
* « Échec » - Le cloud est dans un état de défaillance permanent
* « supprimé » - Le cloud n'est actuellement pas accessible
* « Inconnu » - L'état du cloud ne peut être déterminé




| stateUnready | tableau[chaîne] | Vrai  a| 
Tableau JSON de chaînes JSON, chacune indiquant la raison pour laquelle un cloud ne peut pas passer à l’état « en cours d’exécution » ou est passé à l’état « en échec ». Les valeurs définies sont :

* Longueur minimale : 1
* Longueur maximale : 127




| cloudType | chaîne | Vrai  a| 
Chaîne JSON contenant une valeur indiquant le type de cloud. Les valeurs définies sont :

* « gcp » - Le cloud est fourni par Google
* « azure » – Le cloud est fourni par Microsoft
* « aws » – Le cloud est fourni par Amazon
* « privé » - Le cloud est géré par le client




| identifiant | chaîne | Faux  a| 
Chaîne JSON contenant une valeur indiquant l'ID de l'identifiant qui contient le compte de service pour le cloud. Ceci est requis pour cloudType "gcp", "azure" et "aws". Les valeurs définies sont :

* Conforme au schéma d'identifiant Astra




| ID de compartiment par défaut | chaîne | Faux  a| 
Chaîne JSON contenant l'ID d'un compartiment qui doit être utilisé par défaut lors de la création de sauvegardes pour les applications dans le cloud. Ce paramètre est requis lors du clonage d'applications entre clusters et est utilisé par défaut si aucun compartiment n'est spécifié lors de la création de sauvegardes et de planifications. Valeurs définies :

* Conforme au schéma d'identifiant Astra




| les métadonnées | link:#type_astra_metadata_update["type_astra_metadata_update"] | Vrai  a| 
Métadonnées spécifiques au client et au service associées à la ressource. Les valeurs définies sont :

* Conforme au schéma de métadonnées Astra. Si aucune étiquette n'est spécifiée lors de la création, un objet de métadonnées sera créé sans étiquette. Si aucune étiquette n'est spécifiée lors de la mise à jour, les étiquettes de l'objet de métadonnées, creationTimestamp et createdBy, seront conservées sans modification.


|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-cloud",
  "version": "1.1",
  "id": "1c9512c3-ec62-5ed8-8013-02fc090b9d03",
  "name": "GKE",
  "state": "discovering",
  "stateUnready": [
    "Cloud discovery in progress"
  ],
  "cloudType": "gcp",
  "credentialID": "6fa2f917-f730-41b8-9c15-17f531843b31",
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Réponse

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Réponse

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 



| invalidParams | tableau[link:#invalidParams["invalidParams"]] | Faux  a| 
Liste des paramètres de requête invalides

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Réponse

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Erreur

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 

|===
.Exemple de réponse d'erreur
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Définitions

.Voir les définitions
[%collapsible]
====
[role="api-collapsible-fifth-title"]
type_astra_label

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| nom | chaîne | Vrai  a| 



| valeur | chaîne | Vrai  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_update

Métadonnées spécifiques au client et au service associées à la ressource. Les valeurs définies sont :

* Conforme au schéma de métadonnées Astra. Si aucune étiquette n'est spécifiée lors de la création, un objet de métadonnées sera créé sans étiquette. Si aucune étiquette n'est spécifiée lors de la mise à jour, les étiquettes de l'objet de métadonnées, creationTimestamp et createdBy, seront conservées sans modification.


[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| étiquettes | tableau[link:#type_astra_label["type_astra_label"]] | Faux  a| 



| CréationTimestamp | chaîne | Faux  a| 



| ModificationTimestamp | chaîne | Faux  a| 



| CreatedBy | chaîne | Faux  a| 



| modifiedBy | chaîne | Faux  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| nom | chaîne | Vrai  a| 
Nom du paramètre de requête invalide



| raison | chaîne | Vrai  a| 
Raison pour laquelle le paramètre de requête est invalide

|===
====