---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-topology-v1-clouds-clusters-clusternodes-.html 
summary: Récupérer un nœud de cluster pour un cloud 
---
= Récupérer un nœud de cluster pour un cloud
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/topology/v1/clouds/{cloud_id}/clusters/{cluster_id}/clusterNodes/{clusterNode_id}`#

Renvoie la ressource API Cluster Node stockée dans le corps de la réponse JSON.



== Paramètres

[cols="5*"]
|===
| Nom | Type | Dans | Obligatoire | Description 


| identifiant_compte | chaîne | chemin | Vrai  a| 
ID de la ressource de compte conteneur

* exemple: {{.Account}}




| cloud_id | chaîne | chemin | Vrai  a| 
ID de la ressource cloud



| cluster_id | chaîne | chemin | Vrai  a| 
ID de la ressource de cluster contenant



| clusterNode_id | chaîne | chemin | Vrai  a| 
ID de la collection clusterNode à lister

|===


== Réponse

[source]
----
Status: 200, Returns the stored Cluster Node API resource in the JSON response body.
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 
Type de média de la ressource. Les valeurs définies sont :

* "application/astra-clusterNode"




| version | chaîne | Vrai  a| 
Version de la ressource. Les valeurs définies sont :

* "1,0"




| id | chaîne | Vrai  a| 
Identifiant unique global de la ressource. Les valeurs définies sont :

* Conforme au schéma UUIDv4




| nom | chaîne | Vrai  a| 
Chaîne JSON contenant une valeur indiquant le nom Kubernetes du nœud. Les valeurs définies sont :

* Longueur minimale : 1
* Longueur maximale : 254




| rôle | chaîne | Vrai  a| 
Chaîne JSON contenant une valeur indiquant le rôle Kubernetes du nœud. Les valeurs définies sont :

* Longueur minimale : 1
* Longueur maximale : 254




| étiquettes | tableau[link:#labels["étiquettes"]] | Vrai  a| 
Tableau JSON d'objets JSON, chacun contenant les étiquettes Kubernetes associées au nœud. Si aucune information n'est disponible, ce tableau sera vide.

* Nombre minimum d’articles : 0




| creationTime | chaîne | Vrai  a| 
Chaîne JSON contenant un horodatage ISO 8601 indiquant la date et l'heure de création du nœud. Les valeurs définies sont :

* Conforme au schéma de date et d'heure ISO-8601




| adresse IP externe | chaîne | Vrai  a| 
Chaîne JSON contenant une valeur indiquant l'adresse IP interne du nœud. Les valeurs définies sont :

* Longueur minimale : 1
* Longueur maximale : 63




| IP interne | chaîne | Vrai  a| 
Chaîne JSON contenant une valeur indiquant l'adresse IP externe du nœud. Les valeurs définies sont :

* Longueur minimale : 1
* Longueur maximale : 63




| zone | chaîne | Vrai  a| 
Chaîne JSON contenant une valeur indiquant la zone Kubernetes du nœud. Les valeurs définies sont :

* Longueur minimale : 1
* Longueur maximale : 254




| région | chaîne | Vrai  a| 
Chaîne JSON contenant une valeur indiquant la région Kubernetes du nœud. Les valeurs définies sont :

* Longueur minimale : 1
* Longueur maximale : 254




| instanceType | chaîne | Vrai  a| 
Chaîne JSON contenant une valeur indiquant le type d'instance Kubernetes du nœud. Les valeurs définies sont :

* Longueur minimale : 1
* Longueur maximale : 254




| kernelVersion | chaîne | Vrai  a| 
Chaîne JSON contenant une valeur indiquant la version du noyau utilisée par le nœud. Les valeurs définies sont :

* Longueur minimale : 1
* Longueur maximale : 254




| osImage | chaîne | Vrai  a| 
Chaîne JSON contenant une valeur indiquant l'image du système d'exploitation utilisée par le nœud. Les valeurs définies sont :

* Longueur minimale : 1
* Longueur maximale : 254




| numCpus | chaîne | Vrai  a| 
Chaîne JSON contenant une valeur indiquant le nombre de processeurs attribués au nœud. Les valeurs définies sont :

* Longueur minimale : 1
* Longueur maximale : 254




| mémoire | chaîne | Vrai  a| 
Chaîne JSON contenant une valeur indiquant la quantité de mémoire allouée au nœud. Les valeurs définies sont :

* Longueur minimale : 1
* Longueur maximale : 254




| État | chaîne | Vrai  a| 
Chaîne JSON contenant une valeur indiquant l'état opérationnel du nœud. Les valeurs définies sont :

* « running » - Le nœud fonctionne normalement
* « Provisionnement » - Le nœud est en cours de provisionnement
* « discovering » - Certains aspects du nœud sont en cours de découverte
* « pending » - Le nœud est programmé pour la découverte
* « failed » - Le nœud est en état d'échec
* « inconnu » - L'état du nœud ne peut être déterminé




| les métadonnées | link:#type_astra_metadata["type_astra_metadata"] | Vrai  a| 
Métadonnées spécifiques au client et au service associées à la ressource. Les valeurs définies sont :

* Conforme au schéma de métadonnées Astra


|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-clusterNode",
  "version": "1.0",
  "id": "5df0e09f-2c30-5b8a-b6b6-4fb4063525e4",
  "name": "test-0",
  "role": "node-role.kubernetes.io/worker",
  "labels": [],
  "creationTime": "2020-09-06T04:35:23.593845Z",
  "externalIP": "192.168.12.44",
  "internalIP": "10.0.1.1",
  "zone": "us-west1-c",
  "region": "us-east1",
  "instanceType": "e2-medium",
  "kernelVersion": "4.18.0-147.0.3.el8_1.x86_64",
  "osImage": "Red Hat Enterprise Linux CoreOS 42.81.20191203.0",
  "numCpus": "2",
  "memory": "67108864Ki",
  "state": "running",
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Réponse

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Réponse

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 



| invalidParams | tableau[link:#invalidParams["invalidParams"]] | Faux  a| 
Liste des paramètres de requête invalides

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Réponse

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Erreur

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 

|===
.Exemple de réponse d'erreur
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Définitions

.Voir les définitions
[%collapsible]
====
[role="api-collapsible-fifth-title"]
étiquettes

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| nom | chaîne | Vrai  a| 
Chaîne JSON contenant le nom de l'étiquette Les valeurs définies sont :

* Longueur minimale : 1
* Longueur maximale : 63
* L'expression régulière définie est : "^([\S.]{1,253}\/)?([a-z0-9A-Z_.-]){1,63}$"




| valeur | chaîne | Vrai  a| 
Chaîne JSON contenant la valeur de l'étiquette Defined values are :

* Longueur minimale : 1
* Longueur maximale : 63
* L'expression régulière définie est : "^([a-z0-9A-Z_.-]){1,63}$"


|===
[role="api-collapsible-fifth-title"]
type_astra_label

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| nom | chaîne | Vrai  a| 



| valeur | chaîne | Vrai  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadata

Métadonnées spécifiques au client et au service associées à la ressource. Les valeurs définies sont :

* Conforme au schéma de métadonnées Astra


[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| étiquettes | tableau[link:#type_astra_label["type_astra_label"]] | Vrai  a| 



| CréationTimestamp | chaîne | Vrai  a| 



| ModificationTimestamp | chaîne | Vrai  a| 



| CreatedBy | chaîne | Vrai  a| 



| modifiedBy | chaîne | Faux  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| nom | chaîne | Vrai  a| 
Nom du paramètre de requête invalide



| raison | chaîne | Vrai  a| 
Raison pour laquelle le paramètre de requête est invalide

|===
====