---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/post-accounts-core-v1-credentials.html 
summary: Créer un nouvel identifiant 
---
= Créer un nouvel identifiant
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/credentials`#

Indique les valeurs souhaitées pour la ressource d'API d'identifiant à créer.



== Paramètres

[cols="5*"]
|===
| Nom | Type | Dans | Obligatoire | Description 


| identifiant_compte | chaîne | chemin | Vrai  a| 
ID de la ressource de compte conteneur

* exemple: {{.Account}}


|===


== Corps de la requête

Indique les valeurs souhaitées pour la ressource d'API d'identifiant à créer.

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 
Type de média de la ressource. Les valeurs définies sont :

* "application/astra-identifiant"




| version | chaîne | Vrai  a| 
Version de la ressource. Les valeurs définies sont :

* "1,0"
* "1,1"




| nom | chaîne | Vrai  a| 
Chaîne JSON contenant un nom spécifié par l'utilisateur. Lorsqu'un identifiant est créé pour un utilisateur, le nom sera défini sur l'UUID de cet utilisateur. Les valeurs définies sont :

* Longueur minimale : 1
* Longueur maximale : 127




| keyType | chaîne | Faux  a| 
Chaîne JSON contenant un descripteur de type de validation de données facultatif, spécifié par l'utilisateur, pour le contenu du keyStore. Contraintes de mise à jour étendues :

* Si un keyType n'existe pas dans la ressource et n'est pas spécifié dans une mise à jour, le keyType ne doit plus exister dans la ressource mise à jour.
* Si un keyType n'existe pas dans la ressource et est spécifié dans une mise à jour, le keyType doit être ajouté à la ressource et une validation doit être effectuée. Si la validation échoue, la mise à jour échouera.
* Si un keyType existe dans la ressource et n'est pas spécifié lors d'une mise à jour, le keyType doit être conservé.
* Si un keyType existe dans la ressource et est spécifié lors d'une mise à jour, et que le keyType spécifié correspond au keyType existant, le keyType doit être préservé.
* Si un keyType existe dans la ressource et est spécifié dans une mise à jour, et que le keyType spécifié est différent du keyType existant, la mise à jour échouera. Les valeurs définies sont :
* « generic » - L'identifiant est un ensemble de données génériques. Cela équivaut à ne pas inclure de keyType.
* La validation étendue est effectuée comme suit :
* Une ou plusieurs chaînes de caractères doivent exister dans le keyStore.
* Chaque chaîne de caractères dans le keyStore doit avoir une valeur encodée en base64.
* "passwordHash" - L'identifiant est un hachage de mot de passe.
* La validation étendue est effectuée comme suit :
* Le nom de l'identifiant doit être unique.
* Le nom de l'identifiant doit être égal à un ID de ressource utilisateur valide.
* Le nom de l'identifiant ne doit pas être modifié.
* La ressource utilisateur correspondante doit avoir un "authProvider" de "local".
* Une chaîne de caractères « en clair » doit exister à l'intérieur du keyStore avec une valeur contenant un mot de passe en clair encodé en base64 :
* Le mot de passe en clair doit être conforme à la politique de mot de passe du compte.
* Le mot de passe est stocké sous forme de hachage.
* Une chaîne « change » doit exister à l’intérieur du keyStore avec une valeur contenant une chaîne encodée en base64 « true » ou « false ».
* Un identifiant de type passwordHash ne peut être supprimé que si l’identifiant utilisateur indiqué par le nom n’existe pas.
* "apikey" - L'identifiant est une clé API.
* La validation étendue est effectuée comme suit :
* Une chaîne « apikey » doit exister dans le keyStore, avec une valeur contenant une chaîne arbitraire encodée en base64.
* "kubeconfig" - L'identifiant est un kubeconfig.
* La validation étendue est effectuée comme suit :
* Une chaîne « base64 » doit exister dans le keyStore, avec une valeur contenant un fichier kubeconfig JSON encodé en base64.
* Le fichier kubeconfig ne doit décrire qu'un seul cluster.
* Aucun autre champ ne peut exister à l'intérieur du keyStore.
* « certificat » - L'identifiant est un certificat encodé au format PEM
* La validation étendue est effectuée comme suit :
* Une chaîne « certificate » doit exister dans le keyStore, avec une valeur contenant un certificat PEM encodé en base64.
* « privkey » - L'identifiant est une clé privée encodée au format PEM.
* La validation étendue est effectuée comme suit :
* Une chaîne « privkey » doit exister dans le keyStore, avec une valeur contenant une clé privée PEM encodée en base64.
* "s3" - Indique que les identifiants sont destinés à l'accès au Simple Storage Service (S3).
* La validation étendue est effectuée comme suit :
* Une chaîne « accessKey » doit exister dans la keyStore avec une valeur contenant une clé d'accès S3 encodée en base64.
* Une chaîne « accessSecret » doit exister dans la keyStore avec une valeur contenant un secret d'accès S3 encodé en base64.




| keyStore | link:#keyStore["keyStore"] | Vrai  a| 
Objet JSON contenant des chaînes JSON. Chaque chaîne dans le keyStore représente une partie de l’identifiant. Le nom de chaque chaîne représente la partie de l’identifiant, et la clé-valeur correspondante stocke la valeur de cette partie de l’identifiant au format base64. Les valeurs définies sont :

* Conforme au schéma de données encodées en base64 Aucune limite n'est imposée à la longueur des chaînes.




| valide | chaîne | Faux  a| 
Chaîne JSON indiquant si l'identifiant est valide pour utilisation. La valeur par défaut, si elle est omise, est "true". Les valeurs définies sont :

* « true » – L’identifiant est utilisable.
* « false » – L'identifiant ne doit pas être utilisé.




| validFromTimestamp | chaîne | Faux  a| 
Chaîne JSON contenant un horodatage indiquant quand l’identifiant est valide. Ceux-ci sont utilisés pour la rotation des identifiants. Les valeurs définies sont :

* Conforme au schéma de date et d'heure ISO-8601




| validUntilTimestamp | chaîne | Faux  a| 
Chaîne JSON contenant un horodatage indiquant quand l’identifiant n’est plus valide. Ceux-ci sont utilisés pour la rotation des identifiants. Les valeurs définies sont :

* Conforme au schéma de date et d'heure ISO-8601




| les métadonnées | link:#type_astra_metadata_update["type_astra_metadata_update"] | Faux  a| 
Métadonnées spécifiques au client et au service associées à la ressource. Les valeurs définies sont :

* Conforme au schéma de métadonnées Astra. Si aucune étiquette n'est spécifiée lors de la création, un objet de métadonnées sera créé sans étiquette. Si aucune étiquette n'est spécifiée lors de la mise à jour, les étiquettes de l'objet de métadonnées, creationTimestamp et createdBy, seront conservées sans modification.


|===
.Exemple de requête
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-credential",
  "version": "1.1",
  "name": "myCert",
  "keyStore": {
    "privKey": "SGkh",
    "pubKey": "VGhpcyBpcyBhbiBleGFtcGxlLg=="
  }
}
----
====


== Réponse

[source]
----
Status: 201, Returns the newly created credential resource in the JSON response body.
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 
Type de média de la ressource. Les valeurs définies sont :

* "application/astra-identifiant"




| version | chaîne | Vrai  a| 
Version de la ressource. Les valeurs définies sont :

* "1,0"
* "1,1"




| id | chaîne | Vrai  a| 
Identifiant unique global de la ressource. Les valeurs définies sont :

* Conforme au schéma UUIDv4




| nom | chaîne | Vrai  a| 
Chaîne JSON contenant un nom spécifié par l'utilisateur. Lorsqu'un identifiant est créé pour un utilisateur, le nom sera défini sur l'UUID de cet utilisateur. Les valeurs définies sont :

* Longueur minimale : 1
* Longueur maximale : 127




| keyType | chaîne | Faux  a| 
Chaîne JSON contenant un descripteur de type de validation de données facultatif, spécifié par l'utilisateur, pour le contenu du keyStore. Contraintes de mise à jour étendues :

* Si un keyType n'existe pas dans la ressource et n'est pas spécifié dans une mise à jour, le keyType ne doit plus exister dans la ressource mise à jour.
* Si un keyType n'existe pas dans la ressource et est spécifié dans une mise à jour, le keyType doit être ajouté à la ressource et une validation doit être effectuée. Si la validation échoue, la mise à jour échouera.
* Si un keyType existe dans la ressource et n'est pas spécifié lors d'une mise à jour, le keyType doit être conservé.
* Si un keyType existe dans la ressource et est spécifié lors d'une mise à jour, et que le keyType spécifié correspond au keyType existant, le keyType doit être préservé.
* Si un keyType existe dans la ressource et est spécifié dans une mise à jour, et que le keyType spécifié est différent du keyType existant, la mise à jour échouera. Les valeurs définies sont :
* « generic » - L'identifiant est un ensemble de données génériques. Cela équivaut à ne pas inclure de keyType.
* La validation étendue est effectuée comme suit :
* Une ou plusieurs chaînes de caractères doivent exister dans le keyStore.
* Chaque chaîne de caractères dans le keyStore doit avoir une valeur encodée en base64.
* "passwordHash" - L'identifiant est un hachage de mot de passe.
* La validation étendue est effectuée comme suit :
* Le nom de l'identifiant doit être unique.
* Le nom de l'identifiant doit être égal à un ID de ressource utilisateur valide.
* Le nom de l'identifiant ne doit pas être modifié.
* La ressource utilisateur correspondante doit avoir un "authProvider" de "local".
* Une chaîne de caractères « en clair » doit exister à l'intérieur du keyStore avec une valeur contenant un mot de passe en clair encodé en base64 :
* Le mot de passe en clair doit être conforme à la politique de mot de passe du compte.
* Le mot de passe est stocké sous forme de hachage.
* Une chaîne « change » doit exister à l’intérieur du keyStore avec une valeur contenant une chaîne encodée en base64 « true » ou « false ».
* Un identifiant de type passwordHash ne peut être supprimé que si l’identifiant utilisateur indiqué par le nom n’existe pas.
* "apikey" - L'identifiant est une clé API.
* La validation étendue est effectuée comme suit :
* Une chaîne « apikey » doit exister dans le keyStore, avec une valeur contenant une chaîne arbitraire encodée en base64.
* "kubeconfig" - L'identifiant est un kubeconfig.
* La validation étendue est effectuée comme suit :
* Une chaîne « base64 » doit exister dans le keyStore, avec une valeur contenant un fichier kubeconfig JSON encodé en base64.
* Le fichier kubeconfig ne doit décrire qu'un seul cluster.
* Aucun autre champ ne peut exister à l'intérieur du keyStore.
* « certificat » - L'identifiant est un certificat encodé au format PEM
* La validation étendue est effectuée comme suit :
* Une chaîne « certificate » doit exister dans le keyStore, avec une valeur contenant un certificat PEM encodé en base64.
* « privkey » - L'identifiant est une clé privée encodée au format PEM.
* La validation étendue est effectuée comme suit :
* Une chaîne « privkey » doit exister dans le keyStore, avec une valeur contenant une clé privée PEM encodée en base64.
* "s3" - Indique que les identifiants sont destinés à l'accès au Simple Storage Service (S3).
* La validation étendue est effectuée comme suit :
* Une chaîne « accessKey » doit exister dans la keyStore avec une valeur contenant une clé d'accès S3 encodée en base64.
* Une chaîne « accessSecret » doit exister dans la keyStore avec une valeur contenant un secret d'accès S3 encodé en base64.




| valide | chaîne | Vrai  a| 
Chaîne JSON indiquant si l'identifiant est valide pour utilisation. La valeur par défaut, si elle est omise, est "true". Les valeurs définies sont :

* « true » – L’identifiant est utilisable.
* « false » – L'identifiant ne doit pas être utilisé.




| validFromTimestamp | chaîne | Faux  a| 
Chaîne JSON contenant un horodatage indiquant quand l’identifiant est valide. Ceux-ci sont utilisés pour la rotation des identifiants. Les valeurs définies sont :

* Conforme au schéma de date et d'heure ISO-8601




| validUntilTimestamp | chaîne | Faux  a| 
Chaîne JSON contenant un horodatage indiquant quand l’identifiant n’est plus valide. Ceux-ci sont utilisés pour la rotation des identifiants. Les valeurs définies sont :

* Conforme au schéma de date et d'heure ISO-8601




| les métadonnées | link:#type_astra_metadata_update["type_astra_metadata_update"] | Vrai  a| 
Métadonnées spécifiques au client et au service associées à la ressource. Les valeurs définies sont :

* Conforme au schéma de métadonnées Astra. Si aucune étiquette n'est spécifiée lors de la création, un objet de métadonnées sera créé sans étiquette. Si aucune étiquette n'est spécifiée lors de la mise à jour, les étiquettes de l'objet de métadonnées, creationTimestamp et createdBy, seront conservées sans modification.


|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-credential",
  "version": "1.1",
  "id": "58e26f6a-a631-5122-8e0e-7afe306675c0",
  "name": "myCert",
  "valid": "true",
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Réponse

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Réponse

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 



| invalidFields | tableau[link:#invalidFields["invalidFields"]] | Faux  a| 
Liste des champs invalides du corps de la requête

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Réponse

[source]
----
Status: 409, Conflict
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 



| invalidFields | tableau[link:#invalidFields["invalidFields"]] | Faux  a| 
Liste des champs invalides du corps de la requête

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/10",
  "title": "JSON resource conflict",
  "detail": "The request body JSON contains a field that conflicts with an idempotent value.",
  "status": "409"
}
----
====


== Réponse

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Erreur

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 

|===
.Exemple de réponse d'erreur
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Définitions

.Voir les définitions
[%collapsible]
====
[role="api-collapsible-fifth-title"]
keyStore

Objet JSON contenant des chaînes JSON. Chaque chaîne dans le keyStore représente une partie de l’identifiant. Le nom de chaque chaîne représente la partie de l’identifiant, et la clé-valeur correspondante stocke la valeur de cette partie de l’identifiant au format base64. Les valeurs définies sont :

* Conforme au schéma de données encodées en base64 Aucune limite n'est imposée à la longueur des chaînes.


Association de chaînes de caractères à des chaînes

[role="api-collapsible-fifth-title"]
type_astra_label

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| nom | chaîne | Vrai  a| 



| valeur | chaîne | Vrai  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_update

Métadonnées spécifiques au client et au service associées à la ressource. Les valeurs définies sont :

* Conforme au schéma de métadonnées Astra. Si aucune étiquette n'est spécifiée lors de la création, un objet de métadonnées sera créé sans étiquette. Si aucune étiquette n'est spécifiée lors de la mise à jour, les étiquettes de l'objet de métadonnées, creationTimestamp et createdBy, seront conservées sans modification.


[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| étiquettes | tableau[link:#type_astra_label["type_astra_label"]] | Faux  a| 



| CréationTimestamp | chaîne | Faux  a| 



| ModificationTimestamp | chaîne | Faux  a| 



| CreatedBy | chaîne | Faux  a| 



| modifiedBy | chaîne | Faux  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| nom | chaîne | Vrai  a| 
Nom du paramètre de requête invalide



| raison | chaîne | Vrai  a| 
Raison pour laquelle le paramètre de requête est invalide

|===
[role="api-collapsible-fifth-title"]
invalidFields

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| nom | chaîne | Vrai  a| 
Nom du champ invalide du corps de la requête



| raison | chaîne | Vrai  a| 
Raison pour laquelle le champ du corps de la requête est invalide

|===
====