---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/post-accounts-k8s-v1-apps-executionhookoverrides.html 
summary: 'Créer une nouvelle ressource de remplacement de hook d"exécution pour une application' 
---
= Créer une nouvelle ressource de remplacement de hook d'exécution pour une application
:allow-uri-read: 
:imagesdir: ../media/


[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/accounts/{account_id}/k8s/v1/apps/{app_id}/executionHookOverrides`#

Indique les valeurs souhaitées pour la ressource d'API de remplacement du hook d'exécution à créer.


CAUTION: Cette opération est obsolète.



[[parameters]]
== Paramètres

[cols="5*"]
|===
| Nom | Type | Dans | Obligatoire | Description 


| identifiant_compte | chaîne | chemin | Vrai  a| 
ID de la ressource de compte conteneur

* exemple: {{.Account}}




| app_id | chaîne | chemin | Vrai  a| 
ID de la ressource d'application contenant

|===


[[request-body]]
== Corps de la requête

Indique les valeurs souhaitées pour la ressource d'API de remplacement du hook d'exécution à créer.

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 
Type de média de la ressource. Les valeurs définies sont :

* "application/astra-executionHookOverride"




| version | chaîne | Vrai  a| 
Version de la ressource. Les valeurs définies sont :

* "1,0"




| ID de hook d'exécution | chaîne | Vrai  a| 
Chaîne JSON contenant l'ID d'un hook d'exécution. Les valeurs définies sont :

* Conforme au schéma d'identifiants Astra. Autorise uniquement l'executionHookID d'une ressource de hook d'exécution avec une valeur hookType de « netapp ».




| activé | chaîne | Vrai  a| 
Chaîne JSON indiquant si le hook d'exécution est activé pour l'application spécifiée. Les valeurs possibles sont :

* « true » - Le hook d'exécution est activé et s'exécutera dans un ordre spécifié
* « false » - Le hook d'exécution est désactivé et ne peut pas s'exécuter




| les métadonnées | link:#type_astra_metadata_update["type_astra_metadata_update"] | Faux  a| 
Métadonnées spécifiques au client et au service associées à la ressource. Les valeurs définies sont :

* Conforme au schéma de métadonnées Astra. Si aucune étiquette n'est spécifiée lors de la création, un objet de métadonnées sera créé sans étiquette. Si aucune étiquette n'est spécifiée lors de la mise à jour, les étiquettes de l'objet de métadonnées, creationTimestamp et createdBy, seront conservées sans modification.


|===
.Exemple de requête
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-executionHookOverride",
  "version": "1.0",
  "executionHookID": "eb863cc6-0d9a-454d-8ef7-81b7cac91929",
  "enabled": "false"
}
----
====


[[response]]
== Réponse

[source]
----
Status: 201, Returns the newly created executionHookOverride resource in the JSON response body.
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 
Type de média de la ressource. Les valeurs définies sont :

* "application/astra-executionHookOverride"




| version | chaîne | Vrai  a| 
Version de la ressource. Les valeurs définies sont :

* "1,0"




| id | chaîne | Vrai  a| 
Identifiant unique global de la ressource. Les valeurs définies sont :

* Conforme au schéma UUIDv4




| ID de hook d'exécution | chaîne | Vrai  a| 
Chaîne JSON contenant l'ID d'un hook d'exécution. Les valeurs définies sont :

* Conforme au schéma d'identifiants Astra. Autorise uniquement l'executionHookID d'une ressource de hook d'exécution avec une valeur hookType de « netapp ».




| activé | chaîne | Vrai  a| 
Chaîne JSON indiquant si le hook d'exécution est activé pour l'application spécifiée. Les valeurs possibles sont :

* « true » - Le hook d'exécution est activé et s'exécutera dans un ordre spécifié
* « false » - Le hook d'exécution est désactivé et ne peut pas s'exécuter




| ID de l'application | chaîne | Vrai  a| 
Chaîne JSON contenant l'identifiant associé de l'application avec laquelle la substitution est liée. Les valeurs définies sont :

* Conforme au schéma d'identifiant Astra




| les métadonnées | link:#type_astra_metadata_update["type_astra_metadata_update"] | Vrai  a| 
Métadonnées spécifiques au client et au service associées à la ressource. Les valeurs définies sont :

* Conforme au schéma de métadonnées Astra. Si aucune étiquette n'est spécifiée lors de la création, un objet de métadonnées sera créé sans étiquette. Si aucune étiquette n'est spécifiée lors de la mise à jour, les étiquettes de l'objet de métadonnées, creationTimestamp et createdBy, seront conservées sans modification.


|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-executionHookOverride",
  "version": "1.0",
  "id": "c11af802-5e53-5897-8cd9-2de730494be3",
  "executionHookID": "eb863cc6-0d9a-454d-8ef7-81b7cac91929",
  "enabled": "false",
  "appID": "4b43c2f7-bffa-4f60-b595-d98a05b64bc9",
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


[[response]]
== Réponse

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


[[response]]
== Réponse

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 



| invalidFields | tableau[link:#invalidFields["invalidFields"]] | Faux  a| 
Liste des champs invalides du corps de la requête

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


[[response]]
== Réponse

[source]
----
Status: 409, Conflict
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 



| invalidFields | tableau[link:#invalidFields["invalidFields"]] | Faux  a| 
Liste des champs invalides du corps de la requête

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/10",
  "title": "JSON resource conflict",
  "detail": "The request body JSON contains a field that conflicts with an idempotent value.",
  "status": "409"
}
----
====


[[response]]
== Réponse

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


[[error]]
== Erreur

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 

|===
.Exemple de réponse d'erreur
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


[[definitions]]
== Définitions

.Voir les définitions
[%collapsible]
====
[[type_astra_label]]
[role="api-collapsible-fifth-title"]
type_astra_label

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| nom | chaîne | Vrai  a| 



| valeur | chaîne | Vrai  a| 

|===
[[type_astra_metadata_update]]
[role="api-collapsible-fifth-title"]
type_astra_metadata_update

Métadonnées spécifiques au client et au service associées à la ressource. Les valeurs définies sont :

* Conforme au schéma de métadonnées Astra. Si aucune étiquette n'est spécifiée lors de la création, un objet de métadonnées sera créé sans étiquette. Si aucune étiquette n'est spécifiée lors de la mise à jour, les étiquettes de l'objet de métadonnées, creationTimestamp et createdBy, seront conservées sans modification.


[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| étiquettes | tableau[link:#type_astra_label["type_astra_label"]] | Faux  a| 



| CréationTimestamp | chaîne | Faux  a| 



| ModificationTimestamp | chaîne | Faux  a| 



| CreatedBy | chaîne | Faux  a| 



| modifiedBy | chaîne | Faux  a| 

|===
[[invalidParams]]
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| nom | chaîne | Vrai  a| 
Nom du paramètre de requête invalide



| raison | chaîne | Vrai  a| 
Raison pour laquelle le paramètre de requête est invalide

|===
[[invalidFields]]
[role="api-collapsible-fifth-title"]
invalidFields

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| nom | chaîne | Vrai  a| 
Nom du champ invalide du corps de la requête



| raison | chaîne | Vrai  a| 
Raison pour laquelle le champ du corps de la requête est invalide

|===
====