---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/put-accounts-core-v1-certificates-.html 
summary: Modifier un certificat 
---
= Modifier un certificat
:allow-uri-read: 
:imagesdir: ../media/


[.api-doc-operation .api-doc-operation-put]#PUT# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/certificates/{certificate_id}`#

Remplace l'intégralité de la ressource stockée par le corps de la requête JSON fourni.

*Effets secondaires*

* Un certificat d'autorité de certification mis à jour sera mis à jour dans le magasin de confiance.
* Si un certificat d'autorité de certification (CA) de confiance existant devient non fiable, il sera supprimé du magasin de confiance.
* Si le corps d'un certificat est mis à jour (champ « cert »), l'indicateur « isSelfSigned » doit être inclus pour indiquer l'état du nouveau certificat. Si l'indicateur « isSelfSigned » n'est pas inclus dans ce cas, la valeur sera définie sur « false ».
* Si une mise à jour ne modifie pas le corps du certificat (« champ cert »), l’indicateur « isSelfSigned » est facultatif et la valeur existante sera conservée si elle n’est pas fournie.




[[parameters]]
== Paramètres

[cols="5*"]
|===
| Nom | Type | Dans | Obligatoire | Description 


| identifiant_compte | chaîne | chemin | Vrai  a| 
ID de la ressource de compte conteneur

* exemple: {{.Account}}




| identifiant_certificat | chaîne | chemin | Vrai  a| 
ID de la collection de certificats à lister

|===


[[request-body]]
== Corps de la requête

Remplace l'intégralité de la ressource stockée par le corps de la requête JSON fourni.

*Effets secondaires*

* Un certificat d'autorité de certification mis à jour sera mis à jour dans le magasin de confiance.
* Si un certificat d'autorité de certification (CA) de confiance existant devient non fiable, il sera supprimé du magasin de confiance.
* Si le corps d'un certificat est mis à jour (champ « cert »), l'indicateur « isSelfSigned » doit être inclus pour indiquer l'état du nouveau certificat. Si l'indicateur « isSelfSigned » n'est pas inclus dans ce cas, la valeur sera définie sur « false ».
* Si une mise à jour ne modifie pas le corps du certificat (« champ cert »), l’indicateur « isSelfSigned » est facultatif et la valeur existante sera conservée si elle n’est pas fournie.


[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 
Type de média de la ressource. Les valeurs définies sont :

* "application/astra-certificate"




| version | chaîne | Vrai  a| 
Version de la ressource. Les valeurs définies sont :

* "1,0"
* "1,1"




| id | chaîne | Faux  a| 
Identifiant unique global de la ressource. Les valeurs définies sont :

* Conforme au schéma UUIDv4




| certUse | chaîne | Faux  a| 
Chaîne JSON indiquant l'utilisation du certificat. Si non spécifié, la valeur par défaut est "rootCA". Les valeurs définies sont :

* « rootCA » - Le certificat est un certificat d'autorité de certification (CA) utilisé pour faire confiance à tout certificat signé par cette CA.
* « intermediateCA » - Le certificat est un certificat d’autorité de certification intermédiaire émis par une autorité de certification racine.




| certificat | chaîne | Faux  a| 
Chaîne JSON contenant un certificat au format PKCS-11 encodé en base64 (PEM). Les valeurs définies sont :

* Conforme au schéma de données encodées en base64




| cn | chaîne | Faux  a| 
Chaîne JSON contenant un nom commun extrait du certificat. Les valeurs définies sont :

* Longueur minimale : 1
* Longueur maximale : 511




| expiryTimestamp | chaîne | Faux  a| 
Chaîne JSON contenant un horodatage indiquant la date d'expiration du certificat. Les valeurs définies sont :

* Conforme au schéma de date et d'heure ISO-8601




| isSelfSigned | chaîne | Faux  a| 
Chaîne JSON indiquant si le certificat est auto-signé. Si cette information n'est pas fournie lors de la création, la valeur par défaut est "false". Lors de la mise à jour :

* Si une valeur est fournie, cette valeur sera utilisée.
* Si aucune valeur n'est fournie et que le champ « cert » est inclus dans la mise à jour, la valeur sera définie sur "false".
* Si aucune valeur n'est fournie et que le champ « cert » n'est pas inclus dans la mise à jour, la valeur existante sera conservée. Les valeurs définies sont :
* « true » - Le certificat est auto-signé.
* « false » - Le certificat n'est pas auto-signé.




| trustState | chaîne | Faux  a| 
Chaîne JSON contenant l'une des valeurs énumérées indiquant si le certificat est approuvé. Les valeurs définies sont :

* « non fiable » - Le certificat n'est pas fiable.
* « trusted » - Le certificat est marqué comme fiable.
* « Expiré » - Le certificat a expiré, il n'est donc ni fiable ni non fiable.




| trustStateTransitions | tableau[link:#type_astra_stateTransition["type_astra_stateTransition"]] | Faux  a| 
Tableau JSON d'objets JSON, chacun représentant l'ensemble des transitions d'état autorisées à partir d'un état donné. Chaque objet JSON contient les champs « from » et « to », où la valeur de « from » correspond au nom d'un état et celle de « to » à un tableau d'états de destination autorisés.



| trustStateDesired | chaîne | Faux  a| 
Chaîne JSON contenant une valeur indiquant si le certificat est approuvé. Si cette valeur n'est pas spécifiée lors de la création, la valeur par défaut est "approuvé". Les valeurs définies sont :

* « non fiable » - Le certificat n'est pas fiable.
* « trusted » - Le certificat est marqué comme fiable.




| trustStateDetails | tableau[link:#type_astra_stateDetail["type_astra_stateDetail"]] | Faux  a| 
Tableau JSON d'objets JSON répertoriant des informations supplémentaires sur l'état de confiance du certificat. Si aucun détail n'est disponible, ce tableau sera vide.

* Nombre minimum d'articles : 0




| les métadonnées | link:#type_astra_metadata_update["type_astra_metadata_update"] | Faux  a| 
Métadonnées spécifiques au client et au service associées à la ressource. Les valeurs définies sont :

* Conforme au schéma de métadonnées Astra. Si aucune étiquette n'est spécifiée lors de la création, un objet de métadonnées sera créé sans étiquette. Si aucune étiquette n'est spécifiée lors de la mise à jour, les étiquettes de l'objet de métadonnées, creationTimestamp et createdBy, seront conservées sans modification.


|===
.Exemple de requête
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-certificate",
  "version": "1.1",
  "trustStateDesired": "trusted"
}
----
====


[[response]]
== Réponse

[source]
----
Status: 204, Indicates if the certificate resource was updated.
----


[[response]]
== Réponse

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


[[response]]
== Réponse

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 



| invalidFields | tableau[link:#invalidFields["invalidFields"]] | Faux  a| 
Liste des champs invalides du corps de la requête

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


[[response]]
== Réponse

[source]
----
Status: 409, Conflict
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 



| invalidFields | tableau[link:#invalidFields["invalidFields"]] | Faux  a| 
Liste des champs invalides du corps de la requête

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/10",
  "title": "JSON resource conflict",
  "detail": "The request body JSON contains a field that conflicts with an idempotent value.",
  "status": "409"
}
----
====


[[response]]
== Réponse

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


[[response]]
== Réponse

[source]
----
Status: 503, Service unavailable
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/41",
  "title": "Service not ready",
  "detail": "Currently, the service can't respond to this request.",
  "status": "503"
}
----
====


[[error]]
== Erreur

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 

|===
.Exemple de réponse d'erreur
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


[[definitions]]
== Définitions

.Voir les définitions
[%collapsible]
====
[[type_astra_stateTransition]]
[role="api-collapsible-fifth-title"]
type_astra_stateTransition

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| depuis | chaîne | Vrai  a| 



| pour | tableau[chaîne] | Vrai  a| 

|===
[[additionalDetails]]
[role="api-collapsible-fifth-title"]
additionalDetails

[[type_astra_stateDetail]]
[role="api-collapsible-fifth-title"]
type_astra_stateDetail

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| additionalDetails | link:#additionalDetails["additionalDetails"] | Faux  a| 

|===
[[type_astra_label]]
[role="api-collapsible-fifth-title"]
type_astra_label

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| nom | chaîne | Vrai  a| 



| valeur | chaîne | Vrai  a| 

|===
[[type_astra_metadata_update]]
[role="api-collapsible-fifth-title"]
type_astra_metadata_update

Métadonnées spécifiques au client et au service associées à la ressource. Les valeurs définies sont :

* Conforme au schéma de métadonnées Astra. Si aucune étiquette n'est spécifiée lors de la création, un objet de métadonnées sera créé sans étiquette. Si aucune étiquette n'est spécifiée lors de la mise à jour, les étiquettes de l'objet de métadonnées, creationTimestamp et createdBy, seront conservées sans modification.


[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| étiquettes | tableau[link:#type_astra_label["type_astra_label"]] | Faux  a| 



| CréationTimestamp | chaîne | Faux  a| 



| ModificationTimestamp | chaîne | Faux  a| 



| CreatedBy | chaîne | Faux  a| 



| modifiedBy | chaîne | Faux  a| 

|===
[[invalidParams]]
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| nom | chaîne | Vrai  a| 
Nom du paramètre de requête invalide



| raison | chaîne | Vrai  a| 
Raison pour laquelle le paramètre de requête est invalide

|===
[[invalidFields]]
[role="api-collapsible-fifth-title"]
invalidFields

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| nom | chaîne | Vrai  a| 
Nom du champ invalide du corps de la requête



| raison | chaîne | Vrai  a| 
Raison pour laquelle le champ du corps de la requête est invalide

|===
====