---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/put-accounts-core-v1-subscriptions-.html 
summary: Modifier un abonnement 
---
= Modifier un abonnement
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-put]#PUT# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/subscriptions/{subscription_id}`#

Remplace l'intégralité de la ressource stockée par le corps de la requête JSON fourni, tout en préservant les valeurs clés non modifiables par l'utilisateur.

*Effets secondaires*

* Si l'utilisateur annule l'abonnement, le point de terminaison PUT doit être appelé avec "status": "inactive".
* Lorsque le statut est défini sur « inactif », les frais en attente pour cet abonnement sont envoyés à Zuora et l'abonnement Zuora sera marqué comme « inactif » d'une manière ou d'une autre.




== Paramètres

[cols="5*"]
|===
| Nom | Type | Dans | Obligatoire | Description 


| identifiant_compte | chaîne | chemin | Vrai  a| 
ID de la ressource de compte conteneur

* exemple: {{.Account}}




| id_abonnement | chaîne | chemin | Vrai  a| 
ID de la collection d'abonnements à lister

|===


== Corps de la requête

Remplace l'intégralité de la ressource stockée par le corps de la requête JSON fourni, tout en préservant les valeurs clés non modifiables par l'utilisateur.

*Effets secondaires*

* Si l'utilisateur annule l'abonnement, le point de terminaison PUT doit être appelé avec "status": "inactive".
* Lorsque le statut est défini sur « inactif », les frais en attente pour cet abonnement sont envoyés à Zuora et l'abonnement Zuora sera marqué comme « inactif » d'une manière ou d'une autre.


[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 
Type de média de la ressource. Les valeurs définies sont :

* "application/astra-subscription"




| version | chaîne | Vrai  a| 
Version de la ressource. Les valeurs définies sont :

* "1,0"
* "1,1"
* "1,2"




| id | chaîne | Faux  a| 
Identifiant unique global de la ressource. Les valeurs définies sont :

* Conforme au schéma UUIDv4




| ID de profil client | chaîne | Faux  a| 
La chaîne JSON contenant l’identifiant du profil client à partir de  http://authorize.net["Authorize.net"], qui a été invoqué par l’interface utilisateur, n’est pas définie pour le délai de grâce. Renvoie une chaîne vide lors de l’opération de lecture, si elle n’est pas définie. Les valeurs définies sont :

* Longueur minimale : 0
* Longueur maximale : 63




| paymentFirstName | chaîne | Faux  a| 
Chaîne JSON contenant un prénom complet spécifié par l'utilisateur, utilisé pour la facturation. Spécifié uniquement lorsque l'abonnement est refacturé. Les valeurs définies sont :

* Longueur minimale : 1
* Longueur maximale : 63




| paymentLastName | chaîne | Faux  a| 
Chaîne JSON contenant un nom de famille complet spécifié par l'utilisateur, utilisé pour la facturation. Spécifié uniquement lors du renouvellement de l'abonnement. Les valeurs définies sont :

* Longueur minimale : 1
* Longueur maximale : 63




| paymentAddress | link:#paymentAddress["paymentAddress"] | Faux  a| 
Objet JSON contenant une collection de chaînes JSON spécifiant une adresse de facturation. Spécifié uniquement lorsque l'abonnement est refacturé. Si cette clé existe, les six chaînes JSON qu'elle contient seront présentes. Si rien n'a été fourni par l'utilisateur, la chaîne sera vide.



| ID de profil de paiement | chaîne | Faux  a| 
Chaîne JSON contenant l'identifiant du profil de paiement de http://Authorize.net["Authorize.net"] qui a été invoqué par l'interface utilisateur, non défini pour la période d'essai. Renvoie une chaîne vide lors de l'opération de lecture si non défini. Les valeurs définies sont :

* Longueur minimale : 0
* Longueur maximale : 63




| paymentExpiry | chaîne | Faux  a| 
Chaîne JSON contenant un horodatage indiquant la date d'expiration du mode de paiement. Cette information est obtenue auprès d'authorize.net(http://authorize.net[] et définie par l'interface utilisateur. Les valeurs possibles sont :

* Conforme au schéma de date et d'heure ISO-8601 Ce champ n'est pas renvoyé pour les périodes d'essai.




| purchaseOrderNumber | chaîne | Faux  a| 
Chaîne JSON contenant le numéro de bon de commande pour le mode de paiement. Les valeurs définies sont :

* Longueur minimale : 1
* Longueur maximale : 31




| marketplace | chaîne | Faux  a| 
Chaîne JSON indiquant la marketplace du compte sur laquelle les paiements seront enregistrés. Valeurs définies :

* "netapp"
* "azure"
* "aws"
* "gcp"




| licenseSN | chaîne | Faux  a| 
Chaîne JSON contenant le numéro de série de la licence pour le mode de paiement. Les valeurs définies sont :

* Longueur minimale : 1
* Longueur maximale : 31




| termes | chaîne | Faux  a| 
Chaîne JSON indiquant le niveau actuel du compte. Les valeurs définies sont :

* "essai"
* "payé"




| statut | chaîne | Faux  a| 
Chaîne JSON indiquant l'état actuel de l'abonnement. Les valeurs définies sont :

* "actif"
* "inactif"




| appLimit | nombre | Faux  a| 
Numéro JSON indiquant la limite d'application pour cet abonnement. La valeur -1 indique l'absence de limite.



| namespaceLimit | nombre | Faux  a| 
Numéro JSON indiquant la limite d'espace de noms pour cet abonnement. La valeur -1 indique l'absence de limite.



| subscriptionPeriod | nombre | Faux  a| 
Nombre JSON indiquant la période d'abonnement. La valeur -1 indique une absence de limite. Unité : jours



| gracePeriod | nombre | Faux  a| 
Numéro JSON indiquant le délai de grâce après l'expiration de l'abonnement d'essai ou l'annulation d'un abonnement payant. Unité : jours



| reminderBeforePeriod | nombre | Faux  a| 
Nombre JSON indiquant le nombre de jours avant la fin de l'abonnement d'essai, à partir duquel les notifications client commenceront. La valeur est exprimée en jours avec une valeur de -1 indiquant que ce n'est pas applicable.



| onboardStatus | chaîne | Faux  a| 
Chaîne JSON indiquant l'état actuel de l'onboarding client. Les valeurs valides sont "not started", "in progress", "success", "failed". Les valeurs définies sont :

* "non démarré"
* "en cours"
* "succès"
* "échoué"




| costPerAppUnit | nombre | Faux  a| 
Nombre JSON indiquant le coût par unité d'application. Pour une version d'essai, la valeur est 0. Unité : US dollars



| costPerNamespaceUnit | nombre | Faux  a| 
Nombre JSON indiquant le coût par unité d'espace de noms. Pour une version d'essai, la valeur est 0. Unité : US dollars



| les métadonnées | link:#type_astra_metadata_update["type_astra_metadata_update"] | Faux  a| 
Métadonnées spécifiques au client et au service associées à la ressource. Les valeurs définies sont :

* Conforme au schéma de métadonnées Astra. Si aucune étiquette n'est spécifiée lors de la création, un objet de métadonnées sera créé sans étiquette. Si aucune étiquette n'est spécifiée lors de la mise à jour, les étiquettes de l'objet de métadonnées, creationTimestamp et createdBy, seront conservées sans modification.


|===
.Exemple de requête
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-subscription",
  "version": "1.2",
  "customerProfileID": "2157047189",
  "paymentProfileID": "E7CEB0A9F1BECA32A02493E1B31D5955",
  "paymentExpiry": "2022-05-01T00:00:00Z"
}
----
====


== Réponse

[source]
----
Status: 204, Indicates if the subscription resource was updated.
----


== Réponse

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Réponse

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 



| invalidFields | tableau[link:#invalidFields["invalidFields"]] | Faux  a| 
Liste des champs invalides du corps de la requête

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Réponse

[source]
----
Status: 409, Conflict
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 



| invalidFields | tableau[link:#invalidFields["invalidFields"]] | Faux  a| 
Liste des champs invalides du corps de la requête

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/10",
  "title": "JSON resource conflict",
  "detail": "The request body JSON contains a field that conflicts with an idempotent value.",
  "status": "409"
}
----
====


== Réponse

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Erreur

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 

|===
.Exemple de réponse d'erreur
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/1",
  "title": "Resource not found",
  "detail": "The resource specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Définitions

.Voir les définitions
[%collapsible]
====
[role="api-collapsible-fifth-title"]
paymentAddress

Objet JSON contenant une collection de chaînes JSON spécifiant une adresse de facturation. Spécifié uniquement lorsque l'abonnement est refacturé. Si cette clé existe, les six chaînes JSON qu'elle contient seront présentes. Si rien n'a été fourni par l'utilisateur, la chaîne sera vide.

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| addressCountry | chaîne | Vrai  a| 
Chaîne JSON contenant le nom ou le code pays associé à l'adresse postale, conformément à la norme ISO 3166 Alpha-2. Les valeurs définies sont :

* Longueur minimale : 0
* Longueur maximale : 2




| addressLocality | chaîne | Vrai  a| 
Chaîne JSON contenant la localité (par exemple, la ville) associée à l'adresse postale. Les valeurs définies sont :

* Longueur minimale : 0
* Longueur maximale : 63




| addressRegion | chaîne | Vrai  a| 
Chaîne JSON contenant la région (par exemple, l'État) associée à l'adresse postale. Les valeurs définies sont :

* Longueur minimale : 0
* Longueur maximale : 63




| postalCode | chaîne | Vrai  a| 
Chaîne JSON contenant le code postal associé à l'adresse postale. Les valeurs définies sont :

* Longueur minimale : 0
* Longueur maximale : 63




| streetAddress1 | chaîne | Vrai  a| 
Chaîne JSON contenant l'adresse de rue associée à l'adresse postale. Les valeurs définies sont :

* Longueur minimale : 0
* Longueur maximale : 63




| streetAddress2 | chaîne | Faux  a| 
Chaîne JSON contenant des informations complémentaires facultatives telles que l'adresse de rue, la boîte postale, et plus encore. Les valeurs définies sont :

* Longueur minimale : 0
* Longueur maximale : 63


|===
[role="api-collapsible-fifth-title"]
type_astra_label

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| nom | chaîne | Vrai  a| 



| valeur | chaîne | Vrai  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_update

Métadonnées spécifiques au client et au service associées à la ressource. Les valeurs définies sont :

* Conforme au schéma de métadonnées Astra. Si aucune étiquette n'est spécifiée lors de la création, un objet de métadonnées sera créé sans étiquette. Si aucune étiquette n'est spécifiée lors de la mise à jour, les étiquettes de l'objet de métadonnées, creationTimestamp et createdBy, seront conservées sans modification.


[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| étiquettes | tableau[link:#type_astra_label["type_astra_label"]] | Faux  a| 



| CréationTimestamp | chaîne | Faux  a| 



| ModificationTimestamp | chaîne | Faux  a| 



| CreatedBy | chaîne | Faux  a| 



| modifiedBy | chaîne | Faux  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| nom | chaîne | Vrai  a| 
Nom du paramètre de requête invalide



| raison | chaîne | Vrai  a| 
Raison pour laquelle le paramètre de requête est invalide

|===
[role="api-collapsible-fifth-title"]
invalidFields

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| nom | chaîne | Vrai  a| 
Nom du champ invalide du corps de la requête



| raison | chaîne | Vrai  a| 
Raison pour laquelle le champ du corps de la requête est invalide

|===
====