---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/put-accounts-k8s-v1-apps-executionhooks-.html 
summary: 'Modifier un hook d"exécution pour une application' 
---
= Modifier un hook d'exécution pour une application
:allow-uri-read: 
:imagesdir: ../media/


[.api-doc-operation .api-doc-operation-put]#PUT# [.api-doc-code-block]#`/accounts/{account_id}/k8s/v1/apps/{app_id}/executionHooks/{executionHook_id}`#

Remplace l'intégralité de la ressource stockée par le corps de la requête JSON fourni, tout en préservant les valeurs clés non modifiables par l'utilisateur.

*Effets secondaires*

* La mise à jour d'un point d'exécution existant aura un impact sur toutes les actions futures des applications utilisant ce point d'exécution mis à jour.




[[parameters]]
== Paramètres

[cols="5*"]
|===
| Nom | Type | Dans | Obligatoire | Description 


| identifiant_compte | chaîne | chemin | Vrai  a| 
ID de la ressource de compte conteneur

* exemple: {{.Account}}




| app_id | chaîne | chemin | Vrai  a| 
ID de la ressource d'application contenant



| executionHook_id | chaîne | chemin | Vrai  a| 
ID de la executionHook collection à lister

|===


[[request-body]]
== Corps de la requête

Remplace l'intégralité de la ressource stockée par le corps de la requête JSON fourni, tout en préservant les valeurs clés non modifiables par l'utilisateur.

*Effets secondaires*

* La mise à jour d'un point d'exécution existant aura un impact sur toutes les actions futures des applications utilisant ce point d'exécution mis à jour.


[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 
Type de média de la ressource. Les valeurs définies sont :

* "application/astra-executionHook"




| version | chaîne | Vrai  a| 
Version de la ressource. Les valeurs définies sont :

* "1,0"
* "1,1"
* "1,2"
* "1,3"




| id | chaîne | Faux  a| 
Identifiant unique global de la ressource. Les valeurs définies sont :

* Conforme au schéma UUIDv4




| nom | chaîne | Faux  a| 
Chaîne JSON contenant un nom spécifié par l'utilisateur pour la ressource. Les valeurs définies sont :

* Longueur minimale : 1
* Longueur maximale : 63 Le nom doit être unique pour toutes les ressources de hook d’exécution.




| hookType | chaîne | Faux  a| 
Chaîne JSON définissant le type de hook. Les valeurs définies sont :

* "netapp" - Hook d'exécution fourni par NetApp.
* « custom » - lié à un ID d’application spécifique. Les ressources du hook d’exécution avec hookType « netapp » sont en lecture seule.




| matchingCriteria | tableau[link:#matchingCriteria["matchingCriteria"]] | Faux  a| 
Tableau JSON d'objets JSON décrivant les critères de correspondance pour le hook d'exécution. Lorsque plusieurs matchingCriteria sont spécifiés, un ET logique est appliqué aux critères. Les valeurs définies sont :

* Nombre minimum d’articles : 0
* Nombre maximum d'articles : 10




| action | chaîne | Faux  a| 
Chaîne JSON indiquant l'action que le hook d'exécution lancera si les critères de correspondance sont remplis. Les valeurs définies sont :

* "instantané"
* "sauvegarde"
* "restaurer"
* « basculement »




| scène | chaîne | Faux  a| 
Chaîne JSON indiquant l'étape de l'action à laquelle le hook sera exécuté. Les valeurs définies sont :

* "pre" - Le hook d'exécution sera exécuté avant l'action spécifiée.
* « post » : le hook d’exécution sera lancé après l’action spécifiée. Les valeurs pour l’action « snapshot » sont « pre » et « post ». Les valeurs pour l’action « backup » sont « pre » et « post ». La valeur pour l’action « restore » est « post ». La valeur pour l’action « failover » est « post ».




| hookSourceID | chaîne | Faux  a| 
Chaîne JSON contenant l'identifiant de la source du hook exécuté par ce hook. Les valeurs définies sont :

* Conforme au schéma d'identifiant Astra




| arguments | tableau[chaîne] | Faux  a| 
Tableau JSON de chaînes JSON pour les arguments de la source. Les valeurs définies sont :

* Nombre minimum d’articles : 0
* Nombre maximum d'articles : 16
* Longueur minimale : 0
* Longueur maximale : 127




| ID de l'application | chaîne | Faux  a| 
Chaîne JSON contenant l'identifiant associé de l'application à laquelle ce hook est lié. En essence, d'autres critères de correspondance, si définis. Les valeurs définies sont :

* Conforme au schéma d'identifiant Astra




| activé | chaîne | Faux  a| 
Chaîne JSON indiquant si le hook d'exécution est activé. Les valeurs possibles sont :

* "true" - Le hook d'exécution est activé et sera exécuté comme spécifié.
* « false » - Le hook d’exécution est désactivé et ne sera jamais exécuté. La valeur par défaut est « true ».




| description | chaîne | Faux  a| 
Chaîne JSON contenant une description, spécifiée par l'utilisateur, de la source du hook. Les valeurs définies sont :

* Longueur minimale : 0
* Longueur maximale : 511




| les métadonnées | link:#type_astra_metadata_update["type_astra_metadata_update"] | Faux  a| 
Métadonnées spécifiques au client et au service associées à la ressource. Les valeurs définies sont :

* Conforme au schéma de métadonnées Astra. Si aucune étiquette n'est spécifiée lors de la création, un objet de métadonnées sera créé sans étiquette. Si aucune étiquette n'est spécifiée lors de la mise à jour, les étiquettes de l'objet de métadonnées, creationTimestamp et createdBy, seront conservées sans modification.


|===
.Exemple de requête
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-executionHook",
  "version": "1.3",
  "arguments": [
    "freeze",
    "10"
  ]
}
----
====


[[response]]
== Réponse

[source]
----
Status: 204, Indicates if the executionHook resource was updated.
----


[[response]]
== Réponse

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


[[response]]
== Réponse

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 



| invalidFields | tableau[link:#invalidFields["invalidFields"]] | Faux  a| 
Liste des champs invalides du corps de la requête

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


[[response]]
== Réponse

[source]
----
Status: 409, Conflict
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/10",
  "title": "JSON resource conflict",
  "detail": "The request body JSON contains a field that conflicts with an idempotent value.",
  "status": "409"
}
----
====


[[response]]
== Réponse

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 

|===
.Exemple de réponse
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


[[error]]
== Erreur

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Vrai  a| 



| titre | chaîne | Vrai  a| 



| détail | chaîne | Vrai  a| 



| statut | chaîne | Vrai  a| 



| identifiant de corrélation | chaîne | Faux  a| 

|===
.Exemple de réponse d'erreur
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/1",
  "title": "Resource not found",
  "detail": "The resource specified in the request URI wasn't found.",
  "status": "404"
}
----
====


[[definitions]]
== Définitions

.Voir les définitions
[%collapsible]
====
[[matchingCriteria]]
[role="api-collapsible-fifth-title"]
matchingCriteria

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| type | chaîne | Faux  a| 
Chaîne JSON identifiant le type de critères de correspondance.



| valeur | chaîne | Faux  a| 
Chaîne JSON contenant une expression régulière permettant de rechercher le type de correspondance spécifié. Syntaxe de l'expression régulière : https://github.com/google/re2/wiki/Syntax[]

|===
[[type_astra_label]]
[role="api-collapsible-fifth-title"]
type_astra_label

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| nom | chaîne | Vrai  a| 



| valeur | chaîne | Vrai  a| 

|===
[[type_astra_metadata_update]]
[role="api-collapsible-fifth-title"]
type_astra_metadata_update

Métadonnées spécifiques au client et au service associées à la ressource. Les valeurs définies sont :

* Conforme au schéma de métadonnées Astra. Si aucune étiquette n'est spécifiée lors de la création, un objet de métadonnées sera créé sans étiquette. Si aucune étiquette n'est spécifiée lors de la mise à jour, les étiquettes de l'objet de métadonnées, creationTimestamp et createdBy, seront conservées sans modification.


[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| étiquettes | tableau[link:#type_astra_label["type_astra_label"]] | Faux  a| 



| CréationTimestamp | chaîne | Faux  a| 



| ModificationTimestamp | chaîne | Faux  a| 



| CreatedBy | chaîne | Faux  a| 



| modifiedBy | chaîne | Faux  a| 

|===
[[invalidParams]]
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| nom | chaîne | Vrai  a| 
Nom du paramètre de requête invalide



| raison | chaîne | Vrai  a| 
Raison pour laquelle le paramètre de requête est invalide

|===
[[invalidFields]]
[role="api-collapsible-fifth-title"]
invalidFields

[cols="4*"]
|===
| Nom | Type | Obligatoire | Description 


| nom | chaîne | Vrai  a| 
Nom du champ invalide du corps de la requête



| raison | chaîne | Vrai  a| 
Raison pour laquelle le champ du corps de la requête est invalide

|===
====