---
sidebar: sidebar 
permalink: workflows/wf_clone_app_snapshot.html 
keywords:  
summary: 'Vous pouvez créer une nouvelle application en la clonant à partir d"un snapshot.' 
---
= Cloner une application à partir d'un snapshot
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez créer une nouvelle application en la clonant à partir d'un snapshot.



=== Avant de commencer

Notez les éléments suivants concernant ce flux de travail :

* Un snapshot d'application est utilisé
* L'opération de clonage est effectuée au sein du même cluster



NOTE: Pour cloner une application vers un autre cluster, vous devez mettre à jour le `clusterId` Paramètre JSON dans l'entrée correspondant à votre environnement.



=== 1. Sélectionnez l'application à cloner

Exécutez le flux de travail link:wf_list_man_apps.html["Répertorier les applications"] et sélectionnez l'application à cloner. Plusieurs des valeurs de ressource sont nécessaires pour l'appel REST utilisé pour cloner l'application.



=== 2. Sélectionnez le snapshot à utiliser

Exécutez le flux de travail link:wf_list_snapshots.html["Répertorier les snapshots"] et sélectionnez le snapshot que vous souhaitez utiliser.



=== 3. Clonez l'application

Effectuez l'appel de l'API REST suivant.

[cols="25,75"]
|===
| Méthode HTTP | Chemin 


| POST | /accounts/{account_id}/k8s/v2/apps 
|===


===== Paramètres d'entrée supplémentaires

Outre les paramètres communs à tous les appels API REST, les paramètres suivants sont également utilisés dans les exemples de boucles pour cette étape.

[cols="25,10,10,55"]
|===
| Paramètre | Type | Obligatoire | Description 


| JSON | Corps | Oui. | Fournit les paramètres de l'application clonée. Voir l'exemple ci-dessous. 
|===


===== Exemple d'entrée JSON

[source, json]
----
{
  "type": "application/astra-app",
  "version": "2.0",
  "name": "mysql-clone2",
  "clusterID": "30880586-d579-4d27-930f-a9633e59173b",
  "sourceClusterID": "30880586-d579-4d27-930f-a9633e59173b",
  "namespace": "mysql",
  "snapshotID": "e24515bd-a28e-4b28-b832-f3c74dbf32fb"
}
----


===== Exemple de curl : cloner une application à partir d'un snapshot

[source, curl]
----
curl --location -i --request POST 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/k8s/v2/apps' --header 'Content-Type: application/astra-app+json' --header '*/*' --header 'Authorization: Bearer <API_TOKEN>' --data @JSONinput
----