---
sidebar: sidebar 
permalink: workflows/wf_clone_app_backup.html 
keywords:  
summary: 'Vous pouvez créer une nouvelle application en la clonant à partir d"une sauvegarde.' 
---
= Cloner une application à partir d'une sauvegarde
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez créer une nouvelle application en la clonant à partir d'une sauvegarde.



== Avant de commencer

Notez les éléments suivants concernant ce flux de travail :

* Une sauvegarde d'application est utilisée
* L'opération de clonage est effectuée au sein du même cluster



NOTE: Pour cloner une application vers un autre cluster, vous devez mettre à jour le `clusterId` Paramètre JSON dans l'entrée correspondant à votre environnement.



== Étape 1 : sélectionnez l'application à cloner

Exécutez le flux de travail link:wf_list_man_apps.html["Répertorier les applications"] et sélectionnez l'application à cloner. Plusieurs des valeurs de ressource sont nécessaires pour l'appel REST utilisé pour cloner l'application.



== Étape 2 : sélectionnez la sauvegarde à utiliser

Exécutez le flux de travail link:wf_list_backups.html["Répertoriez les sauvegardes"] et sélectionnez la sauvegarde que vous souhaitez utiliser.



== Étape 3 : cloner l'application

Effectuez l'appel de l'API REST suivant.

.Méthode HTTP et noeud final
Cet appel d'API REST utilise la méthode et le point de terminaison suivants.

[cols="25,75"]
|===
| Méthode HTTP | Chemin 


| POST | /accounts/{account_id}/k8s/v2/qpps 
|===
.Paramètres d'entrée supplémentaires
Outre les paramètres communs à tous les appels API REST, les paramètres suivants sont également utilisés dans les exemples de boucles pour cette étape.

[cols="25,10,10,55"]
|===
| Paramètre | Type | Obligatoire | Description 


| JSON | Corps | Oui. | Fournit les paramètres de l'application clonée. Voir l'exemple ci-dessous. 
|===
.Exemple Curl : cloner une application à partir d'une sauvegarde
[source, curl]
----
curl --request POST \
--location "https://astra.netapp.io/accounts/$ACCOUNT_ID/k8s/v2/apps" \
--include \
--header "Content-Type: application/astra-app+json" \
--header "Accept: */*" \
--header "Authorization: Bearer $API_TOKEN" \
--data  @JSONinput
----
.Exemple d'entrée JSON
[source, json]
----
{
  "type": "application/astra-app",
  "version": "2.0",
  "name": "mysql-clone3",
  "clusterID": "30880586-d579-4d27-930f-a9633e59173b",
  "sourceClusterID": "30880586-d579-4d27-930f-a9633e59173b",
  "namespace": "mysql",
  "backupID": "e24515bd-a28e-4b28-b832-f3c74dbf32fb"
}
----