---
sidebar: sidebar 
permalink: workflows/wf_delete_failed_app.html 
keywords:  
summary: 'Il se peut que vous ne puissiez pas supprimer une application gérée si elle a une sauvegarde ou un snapshot en état d"échec. Dans ce cas, vous pouvez supprimer manuellement l"application.' 
---
= Supprimer une application ayant échoué
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Il se peut que vous ne puissiez pas supprimer une application gérée si elle a une sauvegarde ou un snapshot en état d'échec. Dans ce cas, vous pouvez supprimer manuellement l'application à l'aide du workflow décrit ci-dessous.



== Étape 1 : sélectionnez l'application à supprimer

Exécutez le flux de travail link:wf_list_man_apps.html["Répertorier les applications"] et sélectionnez l'application à supprimer.



== Étape 2 : répertorier les sauvegardes existantes pour l'application

Exécutez le flux de travail link:wf_list_backups.html["Répertoriez les sauvegardes"].



== Étape 3 : supprimez toutes les sauvegardes

Supprimez toutes les sauvegardes de l'application en exécutant le flux de travail link:wf_delete_backup.html["Supprimer une sauvegarde"] pour chaque sauvegarde de la liste.



== Étape 4 : répertoriez les instantanés existants de l'application

Exécutez le flux de travail link:wf_list_snapshots.html["Répertorier les snapshots"].



== Étape 5 : supprimez tous les snapshots

Exécutez le flux de travail link:wf_delete_snapshot.html["Supprime un snapshot"] à partir de chaque instantané de la liste.



== Étape 6 : supprimez l'application

Exécutez le flux de travail link:wf_unmanage_app.html["Annuler la gestion d'une application"] pour supprimer l'application.
