---
sidebar: sidebar 
permalink: workflows/wf_get_man_app.html 
keywords:  
summary: Vous pouvez récupérer toutes les variables de ressource décrivant une seule application. 
---
= Obtenir une application
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez récupérer toutes les variables de ressource décrivant une seule application.



=== Avant de commencer

Vous devez avoir l'ID de l'application que vous souhaitez récupérer. Si nécessaire, vous pouvez utiliser le workflow link:wf_list_man_apps.html["Répertorier les applications"] pour localiser l'application.



=== 1. Obtenez l'application

Effectuez l'appel de l'API REST suivant.

[cols="25,75"]
|===
| Méthode HTTP | Chemin 


| OBTENEZ | /account/{account_id}/k8s/v2/apps/{app_id} 
|===


===== Paramètres d'entrée supplémentaires

Outre les paramètres communs à tous les appels API REST, les paramètres suivants sont également utilisés dans les exemples de boucles pour cette étape.

[cols="25,10,10,55"]
|===
| Paramètre | Type | Obligatoire | Description 


| id de l'application | Chemin | Oui. | Valeur ID de l'application à récupérer. 
|===


===== Exemple de curl : renvoie toutes les données de l'application

[source, curl]
----
curl --location -i --request GET 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/k8s/v2/apps/<APP_ID>' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>'
----