---
sidebar: sidebar 
permalink: workflows/wf_list_snapshots.html 
keywords:  
summary: Vous pouvez afficher la liste des instantanés pris pour une application spécifique. 
---
= Répertorier les snapshots
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez afficher la liste des instantanés pris pour une application spécifique.



=== Avant de commencer

Vous devez disposer de l'ID de l'application pour laquelle vous souhaitez répertorier les instantanés. Si nécessaire, vous pouvez utiliser le workflow link:wf_list_man_apps.html["Répertorier les applications"] pour localiser l'application.



=== 1. Dressez la liste des instantanés

Effectuez l'appel suivant de l'API REST pour afficher la liste des snapshots.

[cols="25,75"]
|===
| Méthode HTTP | Chemin 


| OBTENEZ | /Accounts/{account_ID}/k8s/v1/apps/{app_ID}/appSnaps 
|===


===== Paramètres d'entrée supplémentaires

Outre les paramètres communs à tous les appels API REST, les paramètres suivants sont également utilisés dans les exemples de boucles pour cette étape.

[cols="15,10,10,65"]
|===
| Paramètre | Type | Obligatoire | Description 


| id de l'application | Chemin | Oui. | Identifie l'application propriétaire des snapshots répertoriés. 


| nombre | Requête | Non | Si `count=true` le nombre de snapshots est inclus dans la section métadonnées de la réponse. 
|===


===== Exemple de curl : renvoie tous les snapshots de l'application

[source, curl]
----
curl --location -i --request GET 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/k8s/v1/apps/<APP_ID>/appSnaps' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>'
----


===== Exemple de boucle : renvoie tous les snapshots de l'application et du nombre

[source, curl]
----
curl --location -i --request GET 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/k8s/v1/apps/<APP_ID>/appSnaps?count=true' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>'
----


===== Exemple de sortie JSON

[source, json]
----
{
    "items": [
        {
            "type": "application/astra-appSnap",
            "version": "1.1",
            "id": "1ce34da4-bb0a-4926-b925-4a5d85dda8c2",
            "hookState": "success",
            "metadata": {
                "createdBy": "a530e865-23e8-4e2e-8020-e92c419a3867",
                "creationTimestamp": "2022-10-30T22:44:20Z",
                "modificationTimestamp": "2022-10-30T22:44:20Z",
                "labels": []
            },
            "snapshotAppAsset": "0ebfe3f8-40ed-4bdc-88c4-2144fbda85a0",
            "snapshotCreationTimestamp": "2022-10-30T22:44:33Z",
            "name": "snapshot-david-1",
            "state": "completed",
            "stateUnready": []
        }
    ],
    "metadata": {}
}
----