---
sidebar: sidebar 
permalink: workflows/wf_manage_app.html 
keywords:  
summary: 'Vous pouvez créer une application gérée basée sur une application déjà connue d"Astra dans un espace de noms spécifique. Lorsqu"une application est gérée ou définie par Astra, vous pouvez la protéger en effectuant des sauvegardes et des copies Snapshot.' 
---
= Gérer une application
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez créer une application gérée basée sur une application déjà connue d'Astra dans un espace de noms spécifique. Lorsqu'une application est gérée ou définie par Astra, vous pouvez la protéger en effectuant des sauvegardes et des copies Snapshot.



=== 1. Sélectionnez l'espace de noms

Exécutez le flux de travail link:../workflows/wf_list_namespaces.html["Lister les espaces de noms"] et sélectionnez l'espace de noms.



=== 2. Sélectionnez le cluster

Exécutez le flux de travail link:../workflows_infra/wf_list_clusters.html["Lister les clusters"] et sélectionnez le cluster.



=== 3. Gérer l'application

Effectuez l'appel suivant de l'API REST pour gérer l'application.

[cols="25,75"]
|===
| Méthode HTTP | Chemin 


| POST | /accounts/{account_id}/k8s/v2/apps 
|===


===== Paramètres d'entrée supplémentaires

Outre les paramètres communs à tous les appels API REST, les paramètres suivants sont également utilisés dans les exemples de boucles pour cette étape.

[cols="25,10,10,55"]
|===
| Paramètre | Type | Obligatoire | Description 


| JSON | Corps | Oui. | Fournit les paramètres nécessaires à l'identification de l'application à gérer. Voir l'exemple ci-dessous. 
|===


===== Exemple d'entrée JSON

[source, json]
----
{
  "clusterID": "7ce83fba-6aa1-4e0c-a194-26e714f5eb46",
  "name": "subtext",
  "namespaceScopedResources": [{"namespace": "kube-matrix"}],
  "type": "application/astra-app",
  "version": "2.0"
}
----


===== Exemple de curl : gérer une application

[source, curl]
----
curl --location -i --request POST 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/k8s/v2/apps' --header 'Content-Type: application/astra-app+json' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>'  --data @JSONinput
----