---
sidebar: sidebar 
permalink: workflows/wf_unmanage_app.html 
keywords:  
summary: 'Vous pouvez supprimer une application gérée lorsqu"elle n"est plus nécessaire. La suppression d"une application gérée supprime également les planifications associées.' 
---
= Annuler la gestion d'une application
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez supprimer une application gérée lorsqu'elle n'est plus nécessaire. La suppression d'une application gérée supprime également les planifications associées.



=== Avant de commencer

Vous devez avoir l'ID de l'application que vous souhaitez annuler la gestion. Si nécessaire, vous pouvez utiliser le workflow link:wf_list_man_apps.html["Répertorier les applications"] pour localiser l'application.

Les sauvegardes et snapshots de l'application ne sont pas automatiquement supprimés lorsqu'ils sont supprimés. Si vous n'avez plus besoin des sauvegardes et des snapshots, vous devez les supprimer avant de supprimer l'application.



=== 1. Non géré de l'application

Effectuez l'appel suivant de l'API REST pour supprimer l'application.

[cols="25,75"]
|===
| Méthode HTTP | Chemin 


| SUPPRIMER | /account/{account_id}/k8s/v2/apps/{app_id} 
|===


===== Paramètres d'entrée supplémentaires

Outre les paramètres communs à tous les appels API REST, les paramètres suivants sont également utilisés dans les exemples de boucles pour cette étape.

[cols="25,10,10,55"]
|===
| Paramètre | Type | Obligatoire | Description 


| id de l'application | Chemin | Oui. | Identifie l'application à supprimer. 
|===


===== Exemple de curl : supprimez une application gérée

[source, curl]
----
curl --location -i --request DELETE 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/k8s/v2/apps/<APP_ID>' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>'
----