---
sidebar: sidebar 
permalink: information/additional_resources.html 
keywords: addition resources, additional information, astra family, cloud, netapp cloud, netapp support 
summary: 'Vous trouverez des ressources d"aide supplémentaires sur les services cloud et le support NetApp, ainsi que des informations générales sur REST et cloud.' 
---
= Ressources supplémentaires
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous trouverez des ressources d'aide supplémentaires sur les services cloud et le support NetApp, ainsi que des informations générales sur REST et cloud.



== Astra

* https://docs.netapp.com/us-en/astra-control-center/["Documentation Astra Control Center"^]
+
Documentation relative à la version actuelle du logiciel Astra Control Center déployé dans les locaux du client.

* https://docs.netapp.com/us-en/astra-control-service/["Documentation relative au service après-vente Astra Control"^]
+
Documentation relative à la version actuelle du logiciel Astra Control Service disponible dans le Cloud public.

* https://docs.netapp.com/us-en/astra-data-store/["Documentation Astra Data Store"^]
+
Documentation relative à la version actuelle du logiciel Astra Data Store déployé sur le site du client.

* https://docs.netapp.com/us-en/trident/["Documentation Astra Trident"^]
+
Documentation relative à la version actuelle du logiciel Astra Trident, un orchestrateur de stockage open source géré par NetApp.

* https://docs.netapp.com/us-en/astra-family/["Documentation de la gamme Astra"^]
+
Un emplacement central permettant d'accéder à toute la documentation d'Astra tant pour les déploiements sur site que dans le cloud public.





== Ressources cloud NetApp

* https://cloud.netapp.com/["Solutions cloud NetApp"^]
+
Site central des solutions clouds NetApp.

* https://services.cloud.netapp.com/redirect-to-login?startOnSignup=false["Console NetApp Cloud Central"^]
+
Console de services NetApp Cloud Central avec connexion.

* https://mysupport.netapp.com/["Support NetApp"^]
+
Accédez aux outils de dépannage, à la documentation et à l'assistance technique.





== Concepts DE REPOS et cloud

* Doctorat https://www.ics.uci.edu/~fielding/pubs/dissertation/top.htm["thèse"^] Par Roy Fielding
+
Cette publication a introduit et établi le modèle de développement des applications REST.

* https://auth0.com/["Auth0"^]
+
Il s'agit du service de plateforme d'authentification et d'autorisation utilisé par le service Astra pour l'accès au Web.

* https://www.rfc-editor.org/["Éditeur RFC"^]
+
Source faisant autorité pour les normes Web et Internet, maintenue comme un ensemble de documents RFC numérotés de façon unique.


