---
sidebar: sidebar 
permalink: python/python_before.html 
keywords: python3, requests, urllib3, identity, json 
summary: 'Python est un langage de développement populaire pour l"automatisation des data centers. Avant d"utiliser les fonctions natives de Python avec plusieurs packages courants, vous devez préparer l"environnement et les fichiers d"entrée requis.' 
---
= Avant de commencer
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Python est un langage de développement populaire pour l'automatisation des data centers. Avant d'utiliser les fonctions natives de Python avec plusieurs packages courants, vous devez préparer l'environnement et les fichiers d'entrée requis.


NOTE: En plus d'accéder directement à l'API REST Astra Control avec Python, NetApp propose un kit d'outils qui résume l'API et élimine une partie de la complexité. Voir link:../python/astra_toolkits.html["Kit de développement logiciel NetApp Astra Control Python"] pour en savoir plus.



== Préparation de l'environnement

Les exigences de configuration de base pour exécuter les scripts Python sont décrites ci-dessous.

.Python 3
La dernière version de Python 3 doit être installée.

.Bibliothèques supplémentaires
Les bibliothèques *requêtes* et *urllib3* doivent être installées. Vous pouvez utiliser pip ou un autre outil de gestion Python, selon les besoins de votre environnement.

.Accès réseau
Le poste de travail sur lequel les scripts s'exécutent doit disposer d'un accès réseau et pouvoir accéder à Astra Control. Lorsque vous utilisez le service Astra Control, vous devez être connecté à Internet et être en mesure de vous connecter au service à `https://astra.netapp.io`.

.Informations d'identité
Vous avez besoin d'un compte Astra valide avec l'identifiant de compte et le jeton API. Voir link:../get-started/get_api_token.html["Obtenir un jeton API"] pour en savoir plus.



== Créez les fichiers d'entrée JSON

Les scripts Python s'appuient sur les informations de configuration contenues dans les fichiers d'entrée JSON. Des exemples de fichiers sont fournis ci-dessous.


NOTE: Vous devez mettre à jour les échantillons en fonction de votre environnement.

.Informations d'identité
Le fichier suivant contient le jeton API et le compte Astra. Vous devez transmettre ce fichier aux scripts Python à l'aide de `-i` (ou `--identity`) Paramètre CLI.

[source, json]
----
{
  "api_token": "kH4CA_uVIa8q9UuPzhJaAHaGlaR7-no901DkkrVjIXk=",
  "account_id": "5131dfdf-03a4-5218-ad4b-fe84442b9786"
}
----