---
sidebar: sidebar 
permalink: get-started/get_api_token.html 
keywords: token, obtain token 
summary: 'Vous devez obtenir un jeton API Astra pour utiliser l"API REST Astra Control.' 
---
= Obtenir un jeton API
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous devez obtenir un jeton API Astra pour utiliser l'API REST Astra Control.



== Introduction

Un jeton API identifie l'appelant auprès d'Astra et doit être inclus avec chaque appel d'API REST.

* Vous devez générer un jeton d'API à l'aide de l'interface utilisateur web d'Astra.
* La procédure de génération d'un jeton est la même pour les deux modèles de déploiement Astra. Seule l'URL utilisée pour accéder à Astra est différente.
* L'identité de l'utilisateur avec le token et les autorisations associées sont déterminées par l'utilisateur qui a créé le token.
* Le jeton doit être inclus dans le `Authorization` En-tête de requête HTTP.
* Un jeton n'expire jamais après sa création.
* Vous pouvez révoquer un jeton dans l'interface utilisateur Web Astra.


.Informations associées
* link:../additional/revoke_token.html["Révoquer un jeton API"]




== Créez un jeton API Astra

Les étapes suivantes décrivent comment créer un jeton API Astra.

.Avant de commencer
Vous avez besoin d'informations d'identification pour un compte Astra.

.Description de la tâche
Cette tâche génère un jeton API sur l'interface Web Astra. Vous devez également récupérer l'ID de compte qui est également nécessaire lors de la réalisation d'appels API.

.Étapes
. Connectez-vous à Astra en utilisant les identifiants de votre compte comme suit :
+
** ASTRA Control Service : link:https://astra.netapp.io["https://astra.netapp.io"^]
** ASTRA Control Center : utilisez l'URL de votre environnement local tel qu'établi lors de l'installation


. Cliquez sur l'icône figure en haut à droite de la page et sélectionnez *API Access*.
. Cliquez sur *générer jeton API* sur la page, puis cliquez sur *générer jeton API* dans la fenêtre contextuelle.
. Cliquez sur l'icône pour copier la chaîne de token dans le presse-papiers et l'enregistrer dans votre éditeur.
. Copiez et enregistrez l'ID de compte disponible sur la même page.


.Une fois que vous avez terminé
Lorsque vous accédez à l'API REST d'Astra Control via curl ou un langage de programmation, vous devez inclure le jeton de support d'API dans le protocole HTTP `Authorization` en-tête de demande.
