---
sidebar: sidebar 
permalink: get-started/online_api_ref.html 
keywords: reference, api reference 
summary: 'Vous pouvez accéder aux détails des appels de l"API REST Astra Control, y compris les méthodes HTTP, les paramètres d"entrée et les réponses. Cette référence complète est utile lors du développement d"applications d"automatisation à l"aide de l"API REST.' 
---
= Accédez à la documentation de référence d'Astra API
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez accéder aux détails des appels de l'API REST Astra Control, y compris les méthodes HTTP, les paramètres d'entrée et les réponses. Cette référence complète est utile lors du développement d'applications d'automatisation à l'aide de l'API REST.

.Avant de commencer
Vous avez besoin de identifiants pour vous connecter à l'interface utilisateur web d'Astra pour votre déploiement. La procédure d'accès à la documentation de référence est la même pour Astra Control Service et Astra Control Center. Seule l'URL est différente. Un jeton API n'est pas nécessaire pour accéder au document de référence et l'afficher

.Étapes
. Connectez-vous à Astra en utilisant les identifiants de votre compte comme suit :
+
** ASTRA Control Service : link:https://astra.netapp.io["https://astra.netapp.io"^]
** ASTRA Control Center : utilisez l'URL de votre environnement local tel qu'établi lors de l'installation


. Cliquez sur l'icône figure en haut à droite de la page et sélectionnez *API Access*.
. En haut de la page, cliquez sur l'URL affichée sous *Documentation API*.


.Résultat
La page swagger est lancée dans une nouvelle fenêtre ou un nouvel onglet. Notez que l'URL inclut l'ID de compte du compte avec lequel vous vous êtes connecté.

.Et la suite ?
Vous pouvez éventuellement exécuter un appel d'API à partir de la page swagger. Voir link:../get-started/online_api_call.html["Émettez un appel d'API REST Astra"] pour en savoir plus.
