---
sidebar: sidebar 
permalink: get-started/online_api_ref.html 
keywords: reference, api reference 
summary: 'Vous pouvez accéder aux détails des appels de l"API REST Astra Control, y compris les méthodes HTTP, les paramètres d"entrée et les réponses. Cette référence complète est utile lors du développement d"applications d"automatisation à l"aide de l"API REST.' 
---
= Référence d'API en ligne
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez accéder aux détails des appels de l'API REST Astra Control, y compris les méthodes HTTP, les paramètres d'entrée et les réponses. Cette référence complète est utile lors du développement d'applications d'automatisation à l'aide de l'API REST.


NOTE: La documentation de référence de l'API REST est actuellement fournie avec Astra Control et est disponible en ligne.

.Avant de commencer
Vous avez besoin d'un compte pour Astra Control Center ou Astra Control Service.

.Étapes
. Connectez-vous à Astra à l'aide de vos identifiants de compte.
+
Accédez au site suivant pour le service Astra Control : link:https://astra.netapp.io["https://astra.netapp.io"^]

. Cliquez sur l'icône figure en haut à droite de la page et sélectionnez *API Access*.
. En haut de la page, cliquez sur l'URL affichée sous *Documentation API*.
. Indiquez à nouveau les informations d'identification de votre compte si vous y êtes invité.

